[BE] 예외메시지 구체화
woowacourse-teams/2024-haeng-dong pull request #161
Opened 2024-07-30 04:54 UTC by Arachneee

## issue
- close #118 

## 구현 사항
예외 메시지를 구체화했습니다.
<img width="925" alt="image" src="https://github.com/user-attachments/assets/7c4d6bc6-4ef0-42f0-83ed-eb11c3335508">
`잘못된 멤버 요청입니다.` 의 경우 `"%s은 이미 참여하고 있습니다."`와 `%s은 현재 참여하고 있지 않습니다."`로 구분되어 전달합니다.

## 중점적으로 리뷰받고 싶은 부분(선택)
어떤 부분을 중점으로 리뷰했으면 좋겠는지 작성해주세요.

## 논의하고 싶은 부분(선택)
논의하고 싶은 부분이 있다면 작성해주세요.

## 🫡 참고사항

2024-07-31 05:50 UTC, khabh approved these changes

2024-07-31 06:20 UTC, kunsanglee requested changes
고생하셨어요. 코멘트 보고 반영 부탁드립니다. 👍

2024-07-31 06:20 UTC, kunsanglee commented on server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
> +    protected CurrentMembers(Set<String> members) {
c: `CurrentMembers` 클래스를 상속해서 사용하는 것이 아닌데 protected로 변경한게 좀 어색하네요. 생성자 모두 package-private로 해도 될 것 같아요.

2024-07-31 06:20 UTC, kunsanglee commented on server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
> +    }
r: `HaengdongErrorCode`에 code를 정의한 의미가 보이지 않아요. 에러 코드를 세분화 해서 던지도록 수정해주세요.

2024-07-31 06:20 UTC, kunsanglee commented on server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
> +    INVALID_MEMBER_ACTION("MA_002", "잘못된 맴버 액션입니다."),
r: 같은 예외로 여러 경우가 생기는 경우에 대처할 수 있게 code를 enum으로 정의하는게 좋을 것 같아요.

2024-07-31 10:10 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
> +    protected CurrentMembers(Set<String> members) {
저는 생성자를 public 으로 열어도 크게 문제되지 않는다고 생각합니다.

2024-07-31 10:10 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
> +    }
에러코드를 세분화했습니다.

2024-07-31 10:11 UTC, Arachneee commented on server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
> +    INVALID_MEMBER_ACTION("MA_002", "잘못된 맴버 액션입니다."),
같은 예외로 여러 경우가 생기면 code를 더 추가하는게 좋을 것 같아요.

2024-08-01 01:13 UTC, kunsanglee approved these changes
고생했어요 이만 머지할게요~ 👍

2024-08-01 01:14 UTC, merged