[BE] 행사의 전체 참여자 중 특정 참여자의 멤버 액션을 모두 삭제하는 기능 구현
woowacourse-teams/2024-haeng-dong pull request #185
Opened 2024-08-03 09:28 UTC by kunsanglee

## issue
- close #184 

## API
**엔드포인트**
/api/events/{eventId}/members/{memberName}

**Path Variable**

- eventId: String
- memberName: String

## 구현 사항
토큰으로 행사를 조회하고, memberName과 이름이 같은 맴버 액션을 모두 삭제했다.

## 중점적으로 리뷰받고 싶은 부분(선택)

## 논의하고 싶은 부분(선택)

## 🫡 참고사항

2024-08-03 14:52 UTC, Arachneee requested changes
치명적인 버그가 있어 수정부탁드립니다.

2024-08-03 14:52 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionService.java
> +        memberActionRepository.deleteAllByMemberName(memberName);
r: 다른 행사에 있는 member도 다 지워질 것 같습니다.

2024-08-03 14:52 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
> +    void deleteAllByMemberName(String memberName);
r: 진짜로 다른 행사의 member도 다 지워집니다.

2024-08-03 15:43 UTC, kunsanglee commented on server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
> +    void deleteAllByMemberName(String memberName);
집중해서 코드 리뷰를 잘 하고 계시군요 백호 역시 믿고 있었습니다 👍

2024-08-04 04:20 UTC, 3Juhwan approved these changes
구현 잘해주셨네요! 백호 리뷰도 참 좋습니다.

2024-08-04 04:20 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
> +        memberActionService.deleteMember(token, "참여자");
테스트 코드 넘 좋습니다 👍👍👍👍

2024-08-04 05:41 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionService.java
> +        memberActionRepository.deleteAllByMemberName(event, memberName);
c: event도 조건에 있다는 것을 명시해주세요.

2024-08-04 05:41 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
> +        MemberAction memberAction6 = new MemberAction(action.next(), "참여자", OUT, 1L);
r: action.next() 수정해야합니다.

2024-08-04 06:29 UTC, kunsanglee commented on server/src/main/java/server/haengdong/application/MemberActionService.java
> +        memberActionRepository.deleteAllByMemberName(event, memberName);
`deleteAllByEventAndMemberName`로 수정하여 반영했습니다 👍

2024-08-04 06:29 UTC, kunsanglee commented on server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
> +        MemberAction memberAction6 = new MemberAction(action.next(), "참여자", OUT, 1L);
수정 완료했습니다.

2024-08-04 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/presentation/MemberActionController.java
> +                                             @PathVariable("memberName") String memberName) {
r: 메소드 컨벤션을 지켜주세요.

2024-08-04 06:44 UTC, Arachneee commented on server/src/main/java/server/haengdong/presentation/MemberActionController.java
> +                                             @PathVariable("memberName") String memberName) {
```suggestion
    public ResponseEntity<Void> deleteMember(
                                             @PathVariable("eventId") String token,
                                             @PathVariable("memberName") String memberName
) {
```

2024-08-04 06:57 UTC, Arachneee approved these changes

2024-08-04 06:57 UTC, khabh approved these changes

2024-08-04 07:00 UTC, merged