테스트 데이터 클리너 구현
woowacourse-teams/2024-haeng-dong pull request #199
Opened 2024-08-04 12:10 UTC by 3Juhwan

## issue
- close #58 

## 구현 사항
매 테스트가 종료되고 데이터를 삭제하는 클리너를 구현했습니다. 
클리너는 다음과 같이 동작합니다. 
1. 외래키 제약 조건 해제
2. 모든 테이블 truncate
3. 외래키 제약 조건 설정

## 논의하고 싶은 부분(선택)
- sql이 하드 코딩되어 있는데, 이에 대한 의견이 궁금합니다. 괜찮은가요? 
- 클리너 구현을 컨펌 받고 나서 현재 테스트 코드에 적용하겠습니다.

2024-08-04 14:25 UTC, Arachneee requested changes
테스트 격리에 대해 전혀 신경쓰지 않아도 돼서 좋은 방법 같아요 👍 
Cleaner를 기존 테스트에 적용시키고 merge하는 것이 좋을 것 같습니다.

2024-08-04 14:25 UTC, Arachneee commented on server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java
> +    }
r: clear 를 한번 할 때마다 truncate 쿼리문 생성 쿼리를 날릴 필요는 없을 것 같아요.

2024-08-04 14:25 UTC, Arachneee commented on server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java
> +    }
```suggestion
     private List<String> tableNames;
     
     @PostConstruct
     public void getTableNames() {
                String sql = """
                SELECT TABLE_NAME
                FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = 'PUBLIC'
                """;

        return em.createNativeQuery(sql).getResultList();
    }
        
    @Transactional
    public void clear() {
            em.clear();
            truncate();
    }

    private void truncate() {
        em.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
        tableNames.forEach(tableName -> em.createNativeQuery("TRUNCATE TABLE " + tableName +  "RESTART IDENTITY;").executeUpdate());
        em.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
    }
```
개행이 조금 이상한데 이런 방식으로 빈 등록 후 한번만 날려도 될 것 같습니다.

2024-08-05 00:19 UTC, kunsanglee reviewed
고생 많았어요 👍

2024-08-05 00:19 UTC, kunsanglee commented on server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java
> +    }
r: 쿼리문을 상수로 선언해놓고 재사용 하는 것이 좋을 것 같습니다.
그리고 MySQL 기준 테이블 truncate 하면 auto_increment가 초기화되기 때문에 restart identity 지워도 되겠네요.

```java
static final String referentialFormat = "SET REFERENTIAL_INTEGRITY %b;";
static final String truncateFormat = "TRUNCATE TABLE %s;"

// ... 

private void truncate() {
    em.createNativeQuery(String.format(referentialFormat, false)).executeUpdate();
    tableNames.forEach(tableName -> em.createNativeQuery(String.format(truncateForamt, tableName)).executeUpdate());
    em.createNativeQuery(String.format(referentialFormat, true)).executeUpdate();
}
```

2024-08-05 01:09 UTC, khabh reviewed
👍👍👍👍👍👍

2024-08-05 01:09 UTC, khabh commented on server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java
c: 다음과 같이 truncateTablesQuery를 미리 저장해 놓는 방식으로 해 봐도 좋을 것 같아요
```java
@PostConstruct
    public void getTableNames() {
        String sql = """
                SELECT TABLE_NAME
                FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = 'PUBLIC'
                """;
        List<String> tableNames = em.createNativeQuery(sql).getResultList();
        StringBuilder stringBuilder = new StringBuilder();

        for (String tableName : tableNames) {
            String truncateQuery = String.format(TRUNCATE_FORMAT, tableName);
            stringBuilder.append(truncateQuery);
        }
        truncateTablesQuery = stringBuilder.toString();
    }

    private void truncate() {
        em.createNativeQuery(String.format(REFERENTIAL_FORMAT, false)).executeUpdate();
        em.createNativeQuery(truncateTablesQuery).executeUpdate();
        em.createNativeQuery(String.format(REFERENTIAL_FORMAT, true)).executeUpdate();
    }
```

**실행 결과**
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/fc5a5659-4786-4569-a275-f25307508dd7">

2024-08-05 06:39 UTC, Arachneee approved these changes

2024-08-05 06:39 UTC, khabh approved these changes

2024-08-05 06:40 UTC, merged