[FE] Zustand, react-query 도입 및 적용
woowacourse-teams/2024-haeng-dong pull request #388
Opened 2024-08-17 21:31 UTC by Todari

## issue
- close #369 

## 구현 목적
### 1. api 결과 값을 처리하기 위해 hook 내지 component 내부에서 불필요한 `useState`, `useEffect` 한번에 처리하여 성능과 가독성 저하 해결
```tsx
// useSearchMemberReportList.ts
const useSearchMemberReportList = ({name}: UseSearchMemberReportListParams) => {
  const [memberReportList, setMemberReportList] = useState<MemberReport[]>([]);
  const [memberReportSearchList, setMemberReportSearchList] = useState<MemberReport[]>([]);
  const eventId = getEventIdByUrl();
  const {fetch} = useFetch();

  useEffect(() => {
    const fetchMemberReportList = async () => {

      const memberReportListData = await fetch({queryFunction: () => requestGetMemberReportList({eventId})});
      setMemberReportList(memberReportListData);
    };

    fetchMemberReportList();
  }, []);
  
  useEffect(() => {
    if (name === '') setMemberReportSearchList(memberReportList);

    setMemberReportSearchList(memberReportList.filter(memberReport => memberReport.name.includes(name)));
  }, [name, memberReportList]);

  return {
    memberReportSearchList,
  };
};

export default useSearchMemberReportList;
```
- 예를 들어, `useSearchMemberReportList` hook의 경우 `getMemberReportList`의 결과를 저장하기 위한 `memberReportList` state가 있고, api의 결과값을 해당 state에 할당중입니다.
- 만약, 렌더링 직후 `memberReportSearchList`를 호출하게 된다면, fetch되기 전 state의 기본값인 `[]`인 상태가 될 수 있는 상황이 존재합니다. 따라서, `memberReportSearchList`가 원하는 값을 준다는 보장을 할 수 없습니다.
- react-query를 이용한다면, 불필요한 상태 선언과 `useEffect`를 제거할 수 있으며, error, success, loading 상태의 처리를 내부에서 편하고 정확하게 구현할 수 있을 것으로 판단됩니다.
### 2. 부수효과 및 동기화가 필요한 요청에 대한 불필요한 코드 반복 해결
```tsx
// useStepList.tsx

// ~~

  const refreshStepList = async () => {
    const stepList = await fetch({queryFunction: () => requestGetStepList({eventId})});

    getAllMemberList();
    setStepList(stepList);
  };

  useEffect(() => {
    refreshStepList();
  }, []);

  const updateMemberList = async ({type, memberNameList}: {type: MemberType; memberNameList: string[]}) => {
    await fetch({queryFunction: () => requestPostMemberList({eventId, type, memberNameList})});

    refreshStepList();
  };

  const getAllMemberList = async () => {
    const allMembers = await requestGetAllMemberList({eventId});

    setAllMemberList(allMembers.memberNames);
  };

  const addBill = async (billList: Bill[], onSuccess: () => void) => {
    // TODO: (@weadie) 에러 처리
    await fetch({
      queryFunction: () => requestPostBillList({eventId, billList}),
      onSuccess: () => {
        refreshStepList();
        onSuccess();
      },
    });
  };
  
  // ~~
```
- `useStepList`의 경우, `useContext`를 사용해 전역적으로 서버상태를 관리할 수 있도록 잘 작성된 코드이지만, 몇가지 문제점들이 존재합니다.
- 먼저, `useStepList`이지만, 어디까지가 stepList와 관련한 것인지 애매한 부분이 있습니다. 얘를 들면, 몇몇 api는 내부에 있지만, 어떤 api는 그렇지 않습니다.
- 또한, 내부에서 stepList와 관련된 api 호출등이나 연관된 상태를 관리하는데, 이들 끼리의 동기화를 위해 `refreshStepList` 함수가 반복적으로 호출됩니다.
- `updateMemberList`를 호출하면 memberList POST api 요청을 보내고 `refreshStepList`가 호출되고 이 안에서 `getAllMemberList` 가 호출되며 memberList GET api 요청과 상태 변경을 진행합니다.
- 이는 memberList api 뿐만 아니라, stepList와 연관있는 다른 api에서도 마찬가지입니다.
```tsx
// usePutAndDeleteBillAction.ts
const usePutAndDeleteBillAction = (
  initialValue: InputPair,
  validateFunc: (inputPair: Bill) => ValidateResult,
  onClose: () => void,
) => {

  // ~~
  
  const {refreshStepList} = useStepList();
  
  // ~~
  
  const onSubmit = async (event: React.FormEvent<HTMLFormElement>, inputPair: InputPair, actionId: number) => {
    event.preventDefault();

    const {title, price} = inputPair;

    await fetch({
      queryFunction: () => requestPutBillAction({eventId, actionId, title, price: Number(price)}),
      onSuccess: () => {
        refreshStepList();
        onClose();
      },
    });
  };

  const onDelete = async (actionId: number) => {
    await fetch({
      queryFunction: () => requestDeleteBillAction({eventId, actionId}),
      onSuccess: () => {
        refreshStepList();
        onClose();
      },
    });
  };

  return {
    inputPair,
    handleInputChange,
    handleOnBlur,
    onSubmit,
    onDelete,
    canSubmit,
    errorMessage,
    errorInfo,
  };
};

export default usePutAndDeleteBillAction;
```
- `usePutAndDeleteBillAction` 에서도 stepList를 변경해야 하는 부분이 존재한다면, 계속해서 `refreshStepList`를 호출해 줘야 합니다.
- 이는 추후 다른 api를 만들 때에도, useStepList와 refreshStepList를 빠짐없이 추가해 줘야 하기 때문에 생산성과 가독성을 저하이기도 하며, 휴먼에러를 발생시킬 가능성이 높다고 생각합니다.

### 3.  낙관적 업데이트 및 캐싱 사용에 대한 편리함
- 현재도 react-query 못지 않은 `useFetch`가 구현되어 있지만, 추후 낙관적업데이트 및 캐싱을 통한 사용자 개선을 위해서 react-query를 도입해야 할 필요성을 느꼈습니다.

### 4. 서버 상태에 의존적인 component 해결
- 현재 모든 렌더링 로직이 api 호출 결과에 의존하고 있습니다. 당연한 부분이라고 생각할 수 있겠지만, 서버 요청 데이터와 연관된 부분의 경우 전역 client 상태를 관리하는 방향이 사용자 경험 상에도, 복잡해지는 비동기 처리에 대응하는 개발 경험 상에도 유리할 것이라 생각합니다.
- 예를 들어 `StepList` component는 현재 지나치게 서버에 의존적이고 stepList 호출 결과의 data의 복잡한 구조로 인해 낙관적 업데이트 로직을 작성하는데에도 많은 어려움이 있을 것이라 예상합니다.
- 이를 1:1로 대응하는 flat한 구조의 전역 client 상태를 만들고 이에 대응하는 렌더링 로직을 별도로 구현하는 방법 등이 있을 것이라 생각합니다.

## 구현 내용
### 1. hook 내지 component 내부에서 불필요한 `useState`, `useEffect`제거
- ex) useSearchMemberReportList.ts
- before
```tsx
// useSearchMemberReportList.ts
const useSearchMemberReportList = ({name}: UseSearchMemberReportListParams) => {
  const [memberReportList, setMemberReportList] = useState<MemberReport[]>([]);
  const [memberReportSearchList, setMemberReportSearchList] = useState<MemberReport[]>([]);
  const eventId = getEventIdByUrl();
  const {fetch} = useFetch();

  useEffect(() => {
    const fetchMemberReportList = async () => {

      const memberReportListData = await fetch({queryFunction: () => requestGetMemberReportList({eventId})});
      setMemberReportList(memberReportListData);
    };

    fetchMemberReportList();
  }, []);
  
  useEffect(() => {
    if (name === '') setMemberReportSearchList(memberReportList);

    setMemberReportSearchList(memberReportList.filter(memberReport => memberReport.name.includes(name)));
  }, [name, memberReportList]);

  return {
    memberReportSearchList,
  };
};

export default useSearchMemberReportList;
```
- after
```tsx
// useSearchMemberReportList.ts
const useSearchMemberReportList = ({name}: UseSearchMemberReportListParams) => {
  const [memberReportSearchList, setMemberReportSearchList] = useState<MemberReport[]>([]);

  const {data} = useRequestGetMemberReportList();
  const memberReportList = data ?? [];

  useEffect(() => {
    if (name === '') setMemberReportSearchList(memberReportList);

    setMemberReportSearchList(memberReportList.filter(memberReport => memberReport.name.includes(name)));
  }, [name, memberReportList]);

  return {
    memberReportSearchList,
  };
};

export default useSearchMemberReportList;
```
- 별도의 상태와 useEffect 대신 react-query를 이용해서 불필요한 코드를 줄였습니다.

### 2. react-query의 querykey를 이용하여 불필요한 상태 관리 로직 제거
- ex) usePutAndDeleteBillAction.ts
- before
```tsx
// usePutAndDeleteBillAction.ts

  // ~~

  const onSubmit = async (event: React.FormEvent<HTMLFormElement>, inputPair: InputPair, actionId: number) => {
    event.preventDefault();

    const {title, price} = inputPair;

    await fetch({
      queryFunction: () => requestPutBillAction({eventId, actionId, title, price: Number(price)}),
      onSuccess: () => {
        refreshStepList();
        onClose();
      },
    });
  };

  const onDelete = async (actionId: number) => {
    await fetch({
      queryFunction: () => requestDeleteBillAction({eventId, actionId}),
      onSuccess: () => {
        refreshStepList();
        onClose();
      },
    });
  };
  
  // ~~
```
- after
```tsx
// usePurAndDeleteBillAction.ts

  // ~~

  const onSubmit = async (event: React.FormEvent<HTMLFormElement>, inputPair: InputPair, actionId: number) => {
    event.preventDefault();

    const {title, price} = inputPair;

    putBillAction({actionId, title, price: Number(price)});
    onClose();
  };

  const onDelete = async (actionId: number) => {
    deleteBillAction({actionId});
    onClose();
  };
  
  // ~~
```

- 사용처에서는 put, delete를 요청하는 mutate 함수만을 호출하고, react-query 내부에서 에러핸들링 로직을 처리하도록 변경
- queryKey를 이용해 `stepList`를 갱신하도록 변경
```tsx
// useRequestDeleteBil [...]

2024-08-18 12:27 UTC, jinhokim98 commented on client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
>      setIsOpenBottomSheet(false);
에러가 났을 때 바텀시트가 닫히지 않아야하는데 닫히게 돼서 setIsOpenBottomSheet를 useRequestPostMemberList 안의 onSuccess에 넣어야 할 것 같아요!

2024-08-18 12:28 UTC, jinhokim98 commented on client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
> +    setIsOpenBottomSheet(false);
에러가 났을 때 바텀시트가 닫히지 않아야하는데 닫히게 돼서 setIsOpenBottomSheet를 useRequestPostBillList 안의 onSuccess에 넣어야 할 것 같아요!

2024-08-18 12:34 UTC, jinhokim98 commented on client/src/components/StepList/StepList.tsx
여기서 데이터를 가져올 때 데이터가 없을 경우에 useGetStepList에서 처리해서 내보내주면 더 깔끔하게 작성할 수 있을 것 같아요!

2024-08-18 12:35 UTC, jinhokim98 commented on client/src/constants/queryKeys.ts
> +
query key 정리 👏👏👏

2024-08-18 12:37 UTC, jinhokim98 commented on client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
> +    setIsOpenBottomSheet(false);
오 아니면 아래 useDeleteMemberAction에 있는대로 고쳐봐도 될 듯

requestDeleteMemberAction(
      {actionId},
      {
        onError: () => {
          setAliveActionList(memberActionList);
        },
      },
    );

2024-08-18 12:41 UTC, jinhokim98 commented on client/src/hooks/useRequestDeleteAllMemberList.ts
> +const useRequestDeleteAllMemberList = () => {
useRequest를 앞에 붙임으로써 react-query가 사용되는 훅 의미를 강조하신 것 너무 좋아요~
hooks 폴더 안에 너무 hook들이 많아져서 나중에 폴더 정리를 해도 좋을 것 같아요

2024-08-18 12:43 UTC, jinhokim98 commented on client/src/hooks/useRequestDeleteMemberAction.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.stepList]});
여기 멤버 액션을 지울 때 All member list 캐시를 지워주지 않아도 문제 없을까요?

2024-08-18 12:48 UTC, jinhokim98 commented on client/src/hooks/useRequestGetAllMemberList.ts
> +};
```ts
 return useQuery({
    queryKey: [QUERY_KEYS.allMemberList],
    queryFn: () => requestGetAllMemberList({eventId}),
    select: data => data.memberNames,
  });
```

select 키워드를 이용하면 data를 가공해서 내보낼 수 있어요!
밖에서 필요한 data 형식은 data가 아니라 data.memberNames의 결과이니 훅 안에서 처리해서 내보내는 것이 더 좋아보여서

2024-08-18 12:49 UTC, jinhokim98 commented on client/src/hooks/useRequestGetCurrentInMemberList.ts
> +};
```ts
 return useQuery({
    queryKey: [QUERY_KEYS.currentInMember],
    queryFn: () => requestGetCurrentInMemberList({eventId}),
    select: data => data.members,
  });
```
여기도 동일하게ㅎㅎ

2024-08-18 13:02 UTC, jinhokim98 commented on client/src/hooks/useRequestGetStepList.ts
> +
step list가 로드될 때마다 총 지출 금액을 계산하는 기능 굳굳

2024-08-18 13:05 UTC, jinhokim98 commented on client/src/hooks/useRequestPutAllMemberList.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.memberReport]});
저는 여기에 적는 것이 좋다고 생각을 하는데 또 반복이 되니 계속 적어줘야하는 귀찮음도 있고
소하 웨디 토다리는 어떻게 생각하시나요?

위 3줄이 다른 곳에서 계속 재사용되고 있는 상황인데, 이를 분리해서 별도의 훅으로 만드는 것이 좋다 vs 훅 내부에서 요청이 성공했을 때 명시적으로 어떤 캐시를 지워주는 것을 표현하는 것이 좋다.

2024-08-18 13:07 UTC, jinhokim98 commented on client/src/hooks/useStepList.tsx
> +//   };
여기 있는 모든 로직 다 분리~ 아주 고생했어요!

2024-08-18 13:10 UTC, jinhokim98 commented on client/src/pages/EventPage/HomePage/HomePage.tsx
> +  const {totalExpenseAmount} = useTotalExpenseAmountStore();
깔끔하게 필요한 정보만 잘 가져오게 돼서 너무 좋은 것 같아요

2024-08-18 13:12 UTC, jinhokim98 commented on client/src/pages/EventPage/EventPageLayout.tsx
> +          text={`[행동대장]\n"${eventName}"에 대한 정산을 시작할게요:)\n아래 링크에 접속해서 정산 내역을 확인해 주세요!\nhttps://${env.includes('development') ? 'dev.' : ''}haengdong.pro${ROUTER_URLS.event}/${eventId}/home`}
엇 이 부분 fe-dev와 내용이 다른 것 같은데 확인해보시겠어요?

2024-08-18 13:15 UTC, jinhokim98 commented on client/src/utils/groupActions.ts
> +};
이 부분이 Bill, Member를 나누어서 랜더링 계층을 만들어주는 기능인거죠?

2024-08-18 13:19 UTC, jinhokim98 commented on client/src/App.tsx
> +const queryClient = new QueryClient();
나중에 stale time, gc time에 대해 설정해봐도 좋을 것 같아요.
그리고 retry 횟수도 설정해두면! 이것들은 논의해보면서!

2024-08-18 13:21 UTC, jinhokim98 commented on client/package.json
> +    "@tanstack/react-query": "^5.51.23",
나중에 dev tools도 깔면 query data가 어떻게 변하고 들어오고 있는지 확인이 가능합니다! 이거 너무 유용하다고 생각해서!

2024-08-18 13:22 UTC, jinhokim98 approved these changes

2024-08-18 14:56 UTC, Todari commented on client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
>      setIsOpenBottomSheet(false);
이건 일부러 바꿔놓은게, 우리가 어차피 toast로 에러를 띄워주는데 굳이 onSuccess 를 기다린 다음 성공하면 바텀시트를 내려주는게 사용자경험상 안좋지 않을까? 싶어서 다른 부분도 이와 비슷하게 바꿨서요

2024-08-18 14:56 UTC, Todari commented on client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
> +    setIsOpenBottomSheet(false);
마찬가지

https://github.com/woowacourse-teams/2024-haeng-dong/pull/388#discussion_r1720994993

2024-08-18 14:57 UTC, Todari commented on client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
> +  const {mutate: postMemberList} = useRequestPostMemberList();
그렇게 내보내면 바로 쓸 수 있긴 하겠네용

2024-08-18 14:58 UTC, Todari commented on client/src/hooks/useRequestDeleteMemberAction.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.stepList]});
오.. 세세한 PR 놓치고 갈 뻔했네용

2024-08-18 15:00 UTC, Todari commented on client/src/hooks/useRequestDeleteMemberAction.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.stepList]});
8520c3c

2024-08-18 15:02 UTC, Todari commented on client/src/hooks/useRequestGetAllMemberList.ts
> +};
인지는 하고있었는데, 기존에도 값을 불러온다음 .names, .steps와 같은 식으로 사용하고 있길래 기존대로 적용해줬습니당

2024-08-18 15:02 UTC, Todari commented on client/src/hooks/useRequestGetCurrentInMemberList.ts
> +};
마찬가지

https://github.com/woowacourse-teams/2024-haeng-dong/pull/388#discussion_r1720996017

2024-08-18 15:03 UTC, Todari commented on client/src/hooks/useRequestPutAllMemberList.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.memberReport]});
음 별도로 빼는것도 나쁘지 않을 것 같긴 하네요, key들을 인자로 받아서

2024-08-18 15:06 UTC, Todari commented on client/src/pages/EventPage/EventPageLayout.tsx
> +          text={`[행동대장]\n"${eventName}"에 대한 정산을 시작할게요:)\n아래 링크에 접속해서 정산 내역을 확인해 주세요!\nhttps://${env.includes('development') ? 'dev.' : ''}haengdong.pro${ROUTER_URLS.event}/${eventId}/home`}
url 사용하는 부분인가요??? 작업중에 fe-dev가 머지돼서 따로 머지는 안하고 진행했었어요

2024-08-18 15:06 UTC, Todari commented on client/src/utils/groupActions.ts
> +};
맞아요 아직 구현이 다 안되서 적용은 안된 코드입니다~

2024-08-19 04:35 UTC, jinhokim98 commented on client/src/hooks/useRequestGetAllMemberList.ts
> +};
다들 의견 들어보고 적용하자는 의견이 많으면 고고해도 될 것 같아요!

2024-08-19 04:51 UTC, pakxe requested changes
새로운 라이브러리들 도입하느라 고생많았습니다 토다리 😭😭😭 수정해야할 부분이 엄청 많았을 것 같은데 진짜로.. 다 하나하나 직접 수정했을 거 생각하니 저라면 도망쳤을 듯..

2024-08-19 04:57 UTC, pakxe reviewed
새로운 라이브러리들 도입하느라 고생많았습니다 토다리 😭😭😭 수정해야할 부분이 엄청 많았을 것 같은데 진짜로.. 다 하나하나 직접 수정했을 거 생각하니 저라면 도망쳤을 듯..

2024-08-19 05:33 UTC, pakxe approved these changes
새로운 라이브러리들 도입하느라 고생많았습니다 토다리 😭😭😭 수정해야할 부분이 엄청 많았을 것 같은데 진짜로.. 다 하나하나 직접 수정했을 거 생각하니 저라면 도망쳤을 듯.. 그리고 문서도 꼼꼼하게 써주어서 고마워요. 덕분에 이해하는게 수월해서 너무너무 좋았어요 😻많은 것을 배워갑니다 ㅎ,ㅎ

다만 에러 핸들링에 대해서 추가되면 좋을 내용이 있어 반영해주시면 좋을 것 같아 제안드립니다..!

reactquery의 throwOnError옵션을 최상위 queryClient 에서 사용하면 에러 바운더리를 사용할 수 있는데요. true로 불리언 값을 직접 넘겨준다면, 토스트만 띄우고 에러 바운더리를 안띄우는게 불가능합니다. ture를 준다면 에러 발생시 모두 다 에러 바운더리로 넘어가게 돼요. 그래서 throwOnError 를 조건부 불리언으로 넘겨주어야 하고 마찬가지로 onError도 조건을 주는 방법으로 구현하면 기존과 동일하게 동작할 것 같습니다.

제가 간단하게 시연해본 방법은 아래와 같아욧. [참고한 글](https://velog.io/@ajm0718/React-Query-API-Error-Handling)
```js
const queryClient = new QueryClient({
    defaultOptions: {
      mutations: {
        onError: (error: Error) => {
          if (핸들링 가능한 에러) return toast('오류입니다');
        },
        throwOnError: error => {
          if (핸들링 가능한 에러) return false;
          return true;
        },
      },
    },
  });
```

그리고 이렇게 할 경우 sentry에 로그를 보내는 것도 아마 저기서 해야할 것 같아요. 기존의 방식도 에러토스트, 에러 바운더리, 센트리 로그 모두 최상위에서 수행해주었기 때문입니다,. 

일단 제가 생각해본 방식은 이렇습니다. 토다리가 생각하기에 더 적합한 방법이 있으면 그것으로 기존의 기능과 유사하게 구현해주시면 좋을 것 같아요! 👍⭐️

지금은 데드라인이 얼마 남지 않아서 일단 머지하고 위 사항은 다른 이슈를 만들어 개선하는게 좋을 것 같습니드아!!~

2024-08-19 05:33 UTC, pakxe commented on client/eslint.config.mjs
> +              pattern: '@utils/*',
앗 순서가 잘못되었었군요. 완전 섬세,...✨

2024-08-19 05:33 UTC, pakxe commented on client/package.json
> +    "@tanstack/react-query": "^5.51.23",
좋을 것 같아요!~

2024-08-19 05:33 UTC, pakxe commented on client/src/components/StepList/StepList.tsx
> +  // const {stepList} = useStepList();
요 주석 지워도 될 것 가터유

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
> +  const stepList = stepListData ?? [];
이 변수가 필요한 이유가 있을까요?!

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useRequestGetAllMemberList.ts
> +};
저도 이 방식을 선호합니답 근데 타입이 잘 매칭되는진 모르겠어요.

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useRequestGetEventName.ts
> +import {useQuery} from '@tanstack/react-query';
어우 진쟝 많다... 고생 정말 많았어요

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useRequestGetStepList.ts
> +  const queryResult = useQuery({
디스트럭처링으로 가져와도 될 것 같습니다!

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useRequestPostMemberList.ts
> +    onSuccess: () => {
이거 뭔가 묶어서 할 순 없을까요? 반드시 3개를 모두 초기화해주어야한다면 짜다가 까먹을 수도 있을 것 같기도 하고...?!

2024-08-19 05:33 UTC, pakxe commented on client/src/hooks/useRequestPutAllMemberList.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.memberReport]});
저도  똑같은 커맨트 달았는데, 반드시 3개를 모두 초기화해주어야한다는걸 까먹는 경우가 많을 것 같아서 찬성합니다~

2024-08-19 06:14 UTC, soi-ha approved these changes
확실히 코드가 확 줄어서 너무 너무 좋네요~
고생많았어요 토다리!

2024-08-19 06:14 UTC, soi-ha commented on client/src/hooks/useRequestPutAllMemberList.ts
> +      queryClient.invalidateQueries({queryKey: [QUERY_KEYS.memberReport]});
저두 쿠키 의견에 동의합니다!
저 3줄의 코드를 함수로 만들어서 관리하는 것이 더 좋을 것 같아요!
나중에 변경사항이 발생해도 하나의 파일에서만 관리하면 되니까, 누락될 가능성이 적어져서 좋을 것 같습니다!

2024-08-19 06:14 UTC, soi-ha commented on client/src/store/stepListStore.ts
> +export const useStepListStore = create<State & Action>(set => ({
`use-`로 시작하기 때문에 hook과 혼동될 것 같아요. 그래서 해당 네이밍은 변경됐으면 좋겠습니다!

2024-08-19 06:14 UTC, soi-ha commented on client/src/store/totalExpenseAmountStore.ts
> +export const useTotalExpenseAmountStore = create<State & Action>(set => ({
여기도 마찬가지로 `use-` 사용에 대한 네이밍 변경이 필요해보입니다!

2024-08-19 08:00 UTC, merged