[FE] 지출 내역 추가 변경사항 적용
woowacourse-teams/2024-haeng-dong pull request #414
Opened 2024-08-20 16:13 UTC by soi-ha

## issue
- close #399

## 구현 사항

- 인원 변동 추가 / 지출 내역 추가 Button
    
    디자인시스템 Button을 활용함. 다만, Button width가 부모만큼 커지지 않는 것을 확인.
    각 Button에 `style width: 100%`를 추가하여 부모 width 만큼 늘어나도록 함.
    
    <img width="339" alt="스크린샷 2024-08-20 14 39 00" src="https://github.com/user-attachments/assets/7d92f5ec-dbc1-43e9-a438-88724ce4e772">
    <img width="336" alt="스크린샷 2024-08-20 14 39 07" src="https://github.com/user-attachments/assets/9b1af641-dc00-4e09-a0ea-5d6ab28aa2b2">
   
- isAddEditableItem
    
    해당 상태는 지출 내역 추가를 click 했는지를 나타낸다.
    
    이 상태는 AdminPage에서 만들어져 BillStepItem까지 props drilling을 통해 전해진다.
    context나 store를 사용하여 관리할까 고민했지만, 일단은 props로 넘겨주는 것으로 했다. 추후 어떤 방식으로 하는 것이 좋을 지 논의 후 리팩토링을 꼭 진행해야 한다.
   

### 미 반영 사항

- `시작 인원 추가` 버튼
    
    디자인 시스템에서 변경해야 하기 때문에 일단은 기존에 사용하던 FixedButton을 그대로 사용했음.
    
- 기존의 BottomSheet 미수정
    
    기존에 지출,인원(늦참,탈주) BottomSheet 디자인 및 파일명을 변경하지 않음.

## 🫡 참고사항

2024-08-20 18:04 UTC, Todari requested changes
진짜 어려운 부분일텐데... 고생 많았어요
로직이 어려울까봐 전역store 사용해서 렌더링 하는걸 해놓으려고 했는데...
작업속도가 너무 느려서 ㅠㅠ 미안합니다...
몇가지 에러 comment 달아놓았습니다!

2024-08-20 18:04 UTC, Todari commented on client/src/hooks/useSetBillInput.ts
> +          },
요청 성공하면 값도 지워줘야 할 것 같아요! 현재 지출 내역 추가를 누르면 이전에 추가된 항목이 그대로 initialValue로 들어오고 있습니당

![image](https://github.com/user-attachments/assets/63227c4d-f1fb-4797-a3ef-63d675092059)

2024-08-20 18:04 UTC, Todari commented on client/src/components/StepList/BillStepItem.tsx
> +        )}
isLastBillItem 때문인지, 만약 1차 2차 두개가 있을 때, 지출 내역 추가를 누르면 1차와 2차 각각 EditableItem이 생기는 오류가 있어요! 확인해 주시면 감사하겠습니당~

그리고 아마 BillItem 없을 때 지출내역 추가 안되는거랑 같은 로직 문제일 것 같은데,
추가 인원 들어오고 나서 지출 내역 추가를 누르면 이것도 이전 차수에 포함되는 버그가 있습니다

2024-08-21 00:26 UTC, jinhokim98 approved these changes
어려운 부분이었는데 고생했어요~~~! 대소하

2024-08-21 00:26 UTC, jinhokim98 commented on client/src/components/StepList/BillStepItem.tsx
> +  const totalPrice = step.actions && step.type === 'BILL' ? step.actions.reduce((acc, cur) => acc + cur.price, 0) : 0;
오 step.type이 BILL 인 경우만 BillStep 컴포넌트로 들어오는 줄 알았는데 아니었군요.?

2024-08-21 00:26 UTC, jinhokim98 commented on client/src/components/StepList/StepList.tsx
> +          key={`${step.stepName}${index}`}
stepName이 지금 없으니 이렇게 하는게 맞네요

2024-08-21 00:26 UTC, jinhokim98 commented on client/src/hooks/useSetBillInput.ts
> +
bill 저도 차등 기능 넣을 때 써야하는데 참고할게요..! 굿

2024-08-21 01:15 UTC, soi-ha commented on client/src/hooks/useSetBillInput.ts
> +          },
으잉! 안 들어오는 걸 확인하구 초기화하는 로직을 지웠던건뎅... 다시 추가해야겠네요! 고마워용

2024-08-21 01:20 UTC, soi-ha commented on client/src/components/StepList/BillStepItem.tsx
> +        )}
?! 해당 부분은 이미 반영된 사항인 것 같은데..

2024-08-21 01:21 UTC, Todari commented on client/src/components/StepList/BillStepItem.tsx
> +        )}
ఠࡇఠ ... 잘못확인했었나보ㅓ요 ㅠ
확인이 불가늘한 상태라 일단 어프루브 할게용

2024-08-21 01:24 UTC, soi-ha commented on client/src/components/StepList/BillStepItem.tsx
> +  const totalPrice = step.actions && step.type === 'BILL' ? step.actions.reduce((acc, cur) => acc + cur.price, 0) : 0;
Step에서의 조건 때문에 BillStepItem에서 위 조건문을 추가하게 되었어요!

2024-08-21 03:36 UTC, Todari approved these changes

2024-08-21 05:29 UTC, merged