[BE] 지출로그 추가 기능 구현
woowacourse-teams/2024-haeng-dong pull request #45
Opened 2024-07-18 10:56 UTC by Arachneee

## issue
- close #16

## 구현 사항
지출 로그 추가 기능을 구현했습니다.

## 중점적으로 리뷰받고 싶은 부분(선택)
Service 객체 로직 중심으로 리뷰 받고 싶어요.

## 논의하고 싶은 부분(선택)
BillAction이 Action를 상속하는 구조는 어떨까요?

## 🫡 참고사항

2024-07-18 14:22 UTC, kunsanglee requested changes
서비스 로직 잘 작성해주신 것 같아요.
그 외에 코멘트가 필요한 부분 달아 놨습니다.
고생하셨어요 👍

2024-07-18 14:22 UTC, kunsanglee commented on server/src/main/java/server/haengdong/persistence/BillActionRepository.java
> +    List<BillAction> findByAction_Event(Event event);
c: `@Query`를 사용해서 명시적으로 sql을 작성하는걸 고려하는건 어떨까요? 
현재 `BillAction`이 `Action`을 거쳐야만 `Event`에 접근할 수 있기 때문에 1 뎁스를 더 거쳐야 합니다.
`MemberAction` 에서도 같은 상황인데요, 스키마 관련해서 논의해볼 필요가 있을 것 같아요.

2024-07-18 14:22 UTC, kunsanglee commented on server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
> +        doNothing().when(billActionService).saveAllBillAction(any(), any());
a: 현재 상황에서는 `@MockBean` 을 사용했기 때문에 `BillActionService`를 mocking 하지 않아도 될 것 같아요.

2024-07-18 15:24 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +    }
오! Optional에 map이 되는지 처음 알았네요. 굿👍👍

2024-07-19 06:33 UTC, 3Juhwan reviewed
고생하셨습니다 :) 회의에서 논의할 사항을 코멘트에 남겨 놨습니다. 확인 부탁드려요

2024-07-19 06:33 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +        billActionRepository.saveAll(billActions);
a: 이번 이슈에서 할 필요는 없지만, 좀더 효율적인 저장 방식을 고민해 보면 좋을 것 같아요!

2024-07-19 06:33 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
> +public record BillActionsSaveRequest(List<BillActionSaveRequest> actions) {
```suggestion
public record BillActionsSaveListRequest(List<BillActionSaveRequest> actions) {
```
a: 저희 페어는 위와 같이 네이밍을 했어요. 같이 고민해 보아요.

2024-07-19 06:33 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
> +    public List<BillActionAppRequest> toAppRequests() {
```suggestion
    public List<BillActionAppRequest> toAppRequestList() {
```
a: 이 부분도 동일합니다!

2024-07-19 06:33 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/presentation/BillActionController.java
> +            @RequestBody @Valid BillActionsSaveRequest request
a: 검증에 대해서도 모두 같이 논의가 필요할 것 같아요 :)

2024-07-19 06:33 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +    @DisplayName("지출 내역을 생성한다.")
```suggestion
    @DisplayName("지출 내역을 생성한다")
```

a: 사소한 컨벤션인데, 이 부분도 함께 정해 보아요

2024-07-19 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/persistence/BillActionRepository.java
> +    List<BillAction> findByAction_Event(Event event);
긴 메소드 이름은 명시적으로 sql을 작성하긴 했는데 이거까지 적으면 너무 많아질거 같아요.

2024-07-19 06:42 UTC, Arachneee commented on server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
> +        doNothing().when(billActionService).saveAllBillAction(any(), any());
void 반환이라 필요없는 상황이었네요.

2024-07-19 06:43 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +    private final BillActionRepository billActionRepository;
연관성이 큰 필드를 최상단에 두는 것 좋은 것 같아요~

2024-07-19 07:09 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +        billActionRepository.saveAll(billActions);
billAction이 action을 상속하는 구조가 되면 action을 따로 생성하지 않아도 되서 괜찮을 것 같기도 해요.

2024-07-19 07:11 UTC, Arachneee commented on server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
> +public record BillActionsSaveRequest(List<BillActionSaveRequest> actions) {
List로 자료형을 명시하는 것보단 s로 복수형을 표현하는 것이 간결해서 보기 좋은 것 같아요.

2024-07-19 15:47 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +    }
```suggestion
    @Transactional
    public void saveAllBillAction(String eventToken, List<BillActionAppRequest> requests) {
        Event event = eventRepository.findByToken(eventToken)
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 이벤트 토큰입니다."));
        Action action = createStartAction(event);

        for (BillActionAppRequest request : requests) {
            BillAction billAction = request.toBillAction(action);
            billActionRepository.save(billAction);
            action = action.next();
        }
    }

    private Action createStartAction(Event event) {
        return actionRepository.findLastByEvent(event)
                .map(Action::next)
                .orElse(Action.createFirst(event));
    }
```

2024-07-19 15:51 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +    }
```suggestion
        Action action = createStartAction(event);

        for (BillActionAppRequest request : requests) {
            BillAction billAction = request.toBillAction(action);
            billActionRepository.save(billAction);
            action = action.next();
        }
    }

    private Action createStartAction(Event event) {
        return actionRepository.findLastByEvent(event)
                .map(Action::next)
                .orElse(Action.createFirst(event));
    }
```

Action의 sequence가 Service 층으로 노출하는 것이 불필요하고 sequence의 시작점이 1, 다음 순서가 +1 이라는 로직은 Action의 역할로 판단하여 수정했습니다.

2024-07-20 08:53 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/BillActionService.java
> +    }
좋다고 생각합니다. #47 도 동일한 구조로 수정했습니다.

2024-07-20 11:00 UTC, kunsanglee requested changes
의견이 궁금한 부분이 조금 있었고, 로직 관련하여 남길 리뷰는 없었던 것 같아요.
코멘트 확인해보시고 의견 남겨주세요. 
고생 많으셨습니다 👍

2024-07-20 15:10 UTC, Arachneee commented on server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
> +    private BillActionService billActionService;
상속구조를 활용해서 컨트롤러 테스트간의 중복된 객체를 제거하면 좋을 것 같아요. 상속구조를 활용하면 Spring 컨테이너를 클래스마다 새로 띄우지 않는 장점도 있습니다.

2024-07-20 15:12 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +                );
스택처럼 순차적으로 저장이 되었는지 확인하고 싶어서 정렬을 했습니다.
테스트코드에 로직이 있는 것이 불편하긴 하네요. 더 좋은 방법을 생각해봐야겠어요.

2024-07-20 15:28 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/BillAction.java
>      private Action action;
좋아요~ 반영완료했습니다.

2024-07-20 15:31 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +        Event event = eventRepository.save(new Event("감자", token));
좋아요~ 반영 완료했습니다.

2024-07-20 15:46 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
> +    private BillActionService billActionService;
이상의 의견대로 정렬하는 것이 좋다고 생각합니다. 정렬 기준은 뭐든 선택만 하면 될 것 같습니다. 
백호 의견대로 중복되는 것은 별도의 클래스로 분리하면 좋을 것 같습니다. 테스트 클래스가 더 많아지면 그때 분리해 보는 건 어떨까요?

2024-07-20 15:55 UTC, 3Juhwan approved these changes
리뷰 반영하느라 고생하셨습니다 😀 
마지막으로 사소한 부분 코멘트 남겼으니 확인해 주세요 :)

+ 추가로, 테스트 코드에 FE 크루의 이름을 넣는 것은 어떠한가요? BE 코드지만 우리 같은 팀원 이름이 모두 담기면 좋을 것 같아요 😍

2024-07-20 15:55 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/domain/BillActionTest.java
> +    @DisplayName("앞뒤 공백을 제거한 title이 2 ~ 30자가 아니면 지출을 생성할 수 없다.")
a: 
```suggestion
    @DisplayName("앞뒤 공백을 제거한 타이틀 길이가 2 ~ 30자가 아니면 지출을 생성할 수 없다.")
```

2024-07-20 15:55 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/domain/BillActionTest.java
> +    @ValueSource(strings = {" 감 ", "", " ", "감자감자감자감자감자감자백호백호백호백호백호감자감자감자감자감자감자백호백호백호백호백호"})
```suggestion
    @ValueSource(strings = {" 감 ", "", " ", "1234567890123456789012345678901"})
```
c: 엣지 케이스인 정확한 31자를 검증하면 좋겠습니다. 저는 길이 제한을 검증할 때 31자라는 것을 쉽게 인지할 수 있는 방식을 선호합니다.

2024-07-20 16:07 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/domain/BillActionTest.java
> +    }
> 이런 과정을 통해 인지했고, 만약 클라이언트에서 요구하는 DTO에 대한 수정사항으로 인해 변경하다가 검증 애너테이션을 잘못 달거나, 빼먹는다면? 또는 DTO를 통해 생성하지 않고 객체를 생성할 시 실수를 인지하기 어려울 수 있겠다는 느낌을 받았습니다.

controller 테스트에서 해당 어노테이션에 대한 검증을 하면 해결할 수 있지 않을까요? 

인지 비용이 든다는 것을 이해해요. 우리 모두 코드 작성 방식이 달라서, 누군가는 인지 비용이 클 수 있을 것 같아요. 코드 컨벤션을 정함에 있어서 기준이 모두의 인지 비용을 줄이는 방향이라는 생각이 드네요. 도메인 테스트에서는 이상이 큰 비용을 부담하는 것 같고요. 그 비용이 크다면, 저는 널 검증을 도메인에서 하고 비용을 줄이는 편을 택하겠어요 :)

2024-07-20 16:17 UTC, kunsanglee commented on server/src/test/java/server/haengdong/domain/BillActionTest.java
> +    }
일전에 이미 논의한 주제라서 지금 변경이 필요하다고 하는건 아닙니다. 개인적인 인지 비용은 시간이 조금 지나면 익숙해져서 해결될 것 같습니다. 다만 혹시라도 앞서 언급한 예상되는 실수가 실제로 발생하면 그 때 가서 도메인에서의 검증을 재고해봐도 늦지 않을 것 같아요.

2024-07-20 16:19 UTC, kunsanglee commented on server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
> +    private BillActionService billActionService;
망쵸 의견에 동의합니다. 제 생각에도 최소한 지금 진행하고 있는 이슈 두 건이 모두 머지된 이후에 테스트 상속을 고려하는 것이 적절할 것 같아요.

2024-07-21 02:03 UTC, khabh commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +                );
이상의 제안대로 정렬 로직을 제외하는 대신 다음과 같이 assert 부분을 sequence에 대한 검증도 가능하도록 수정했습니다~
```java
assertThat(actions).extracting(BillAction::getTitle, BillAction::getPrice, BillAction::getSequence)
                .containsExactlyInAnyOrder(
                        tuple("뽕족", 10_000L, 1L),
                        tuple("인생맥주", 15_000L, 2L)
                );
```

2024-07-21 02:41 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +                );
`extracting` 괜찮을까요? 깜박하고 언급하지 않았네요. 저는 테스트에 리플렉션을 지양하는 편입니다. 다만, 지금은 그대로 가도 괜찮다고 생각해요.

2024-07-21 04:27 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/BillActionServiceTest.java
> +                );
getter가 열려있는 상황이라 extracting을 굳이 쓸 필요는 없을 것 같아요.

2024-07-21 05:40 UTC, kunsanglee approved these changes

2024-07-21 05:41 UTC, merged