[BE] 인원 변동 기능 구현
woowacourse-teams/2024-haeng-dong pull request #47
Opened 2024-07-19 07:15 UTC by 3Juhwan

## issue
- close #14 

## 구현 사항
인원 변동 기능을 구현했습니다. 

## 중점적으로 리뷰받고 싶은 부분(선택)
- MemberActionService.class 
- MemberActionFactory.class

## 논의하고 싶은 부분(선택)
#45 과 유사한 로직을 담고 있어, 컨벤션과 구현 방식에 있어 함께 논의가 필요합니다.

2024-07-19 08:13 UTC, Arachneee requested changes

2024-07-19 08:13 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +import server.haengdong.persistence.ActionRepository;
r: Factory class가 꼭 필요할까요?
무엇보다 domain 패키지에 위치하는데 application, persistence 패키지 하고 순환도 일어나고 있습니다.

2024-07-19 08:13 UTC, Arachneee commented on server/src/main/java/server/haengdong/persistence/ActionRepository.java
> +    Optional<Action> findLastByEvent(@Param("event") Event event);
c: `@Param("event")` 안 붙여도 좋을 것 같아요.

2024-07-19 08:27 UTC, Arachneee requested changes

2024-07-19 08:27 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +        if (!isAvailableAction(memberActions, action.name(), action.status())) {
c: `!isAvailableAction`  대신 `isUnavailableAction` 은 어떤가요?

2024-07-19 08:27 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/MemberActionStatus.java
> +    }
c: 굳이 메소드를 안만들고 `MemberActionStatus.IN == memberActionStatus` 로 사용해도 읽는데 어려움은 없을 것 같아요.

2024-07-19 08:29 UTC, khabh commented on server/src/main/java/server/haengdong/application/MemberActionService.java
> +    private final MemberActionFactory memberActionFactory;
```suggestion
    private final MemberActionFactory memberActionFactory;
    private final MemberActionRepository memberActionRepository;
    private final EventRepository eventRepository;
```

2024-07-19 08:33 UTC, Arachneee commented on server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
> +    List<MemberAction> findAllByEvent(@Param("event") Event event);
c: 지금 성능상 문제는 없지만 Lazy 로딩이 걸려있어 fetch join을 활용하면 좋을 것 같아요.

2024-07-19 08:41 UTC, khabh commented on server/src/main/java/server/haengdong/application/request/MemberActionSaveListAppRequest.java
> +public record MemberActionSaveListAppRequest(List<MemberActionSaveAppRequest> actions) {
```suggestion
public record MemberActionsSaveAppRequest(List<MemberActionSaveAppRequest> actions) {
```

2024-07-19 15:30 UTC, khabh requested changes
MemberAction 생성 시 처리해 줘야 하는 예외적인 상황들에 대한 검증과 테스트 모두 꼼꼼하게 작성해 주셨네요 👍
코멘트 몇 개 남겼으니 확인해 주세요~

2024-07-19 15:30 UTC, khabh commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +        return MemberActionStatus.isMemberStatusIn(memberActionStatus);
c: validateAction()을 호출하기 전 다음과 같이 memberActions에 대한 정렬을 수행하면 가독성이 더 좋을 것 같아요

```java
memberActions.sort(Comparator.comparing(MemberAction::getSequence).reversed());
```

```suggestion
        for (MemberAction action : actions) {
            if (action.isSameName(name)) {
                return action.isAvailable(memberActionStatus);
            }
        }
        return MemberActionStatus.IN == memberActionStatus;
```

2024-07-19 15:30 UTC, khabh commented on server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
> +    @DisplayName("입장하지 않았을 경우 들어올 수 없다")
```suggestion
    @DisplayName("입장하지 않았을 경우 퇴장할 수 없다")
```

2024-07-19 15:30 UTC, khabh commented on server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
> +    }
c: 추가로 행사에 참여 중인 멤버에 대해 IN 액션 요청이 들어왔을 때에 대한 예외 테스트도 있으면 좋을 것 같습니다!

2024-07-19 15:30 UTC, khabh commented on server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
> +    @Query("select m from MemberAction m where m.action.event = :event")
ActionRepository에서는 select나 from 같은 키워드를 대문자로 작성했는데 이 부분에 대한 컨벤션 논의도 필요할 것 같네요

2024-07-20 05:23 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
> +    @Query("select m from MemberAction m where m.action.event = :event")
이상과 망쵸는 소문자 컨벤션을 선호합니다. 쉬프트를 누르는 수고를 덜 수 있기 때문이에요 :)

2024-07-20 05:37 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/persistence/ActionRepository.java
> +    Optional<Action> findLastByEvent(@Param("event") Event event);
망쵸를 배려하여 모두가 붙이기로 했습니다 😁

2024-07-20 06:17 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +        return MemberActionStatus.isMemberStatusIn(memberActionStatus);
제안 감사합니다 :) 부분적으로 수용했는데 `reversed()`는 반영하지 않았어요. 

- 이전 로그를 기반으로 역추적하는 검증 로직을 작성했는데요. 
- 로그의 마지막 부분부터 반대로 스캔하는 방식이에요. 
- 이것이 검증 로직에 드러나야 할 것 같아요. 

코드를 수정하고 의견 부탁드려요!

2024-07-20 06:21 UTC, kunsanglee commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +import server.haengdong.persistence.ActionRepository;
MemberActionFactory 가 domain 패키지에 있었는데, 현재는 application 패키지로 옮겨서 패키지 의존성 문제를 해결했습니다.

2024-07-20 12:24 UTC, khabh commented on server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
> +class MemberActionFactoryTest {
r: 테스트 클래스에서 전반적으로 다 예외 발생 여부에 대한 테스트만 수행하고 있어서, createMemberActions() 호출 시 생성되는 반환값에 대한 검증이 추가되면 더 좋을 것 같습니다 :)

2024-07-20 12:24 UTC, khabh commented on server/src/main/java/server/haengdong/domain/MemberActionFactory.java
> +        return MemberActionStatus.isMemberStatusIn(memberActionStatus);
코드를 처음 본 사람이 validateAction 메서드 호출 시 로그를 반대로 정렬해서 줘야 한다는 사실을 파악하기는 어려울 테니, 부분적으로 수용한 현재 코드가 더 예측하기 쉽겠네요. 잘 수정된 것 같습니다!

2024-07-20 12:30 UTC, khabh reviewed
리뷰 잘 반영해서 리팩토링 해주셨네요
수고하셨습니다~

2024-07-20 12:31 UTC, khabh approved these changes

2024-07-20 14:03 UTC, kunsanglee reviewed
자체 리뷰 남겼습니다. 
리뷰어분들도 의견 주세요 감사합니다.

2024-07-20 14:04 UTC, Arachneee commented on server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
> +    @Query("select m from MemberAction m where m.action.event = :event")
저도 소문자 선호합니다.

2024-07-20 14:25 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +                return action.isSameStatus(status);
저도 memberName, memberAction으로 하는 것이 더 좋아보여요.

2024-07-20 14:31 UTC, Arachneee reviewed
c: 검증 로직을 처음에 역순으로 정렬한뒤 stream 을 활용해서 함수형으로 표현하는 것은 어떨까요?

for문 역방향 탐색이 읽기 조금 어려웠어요.

---
다른 검증 방법으로 `List<MemberAction>`를 전부 가져오는 것이 아닌 
1. 현재 남아있는 member names 계산
2. OUT 시도시 member names에 존재확인
3. IN 시도시 member names에 없는지 확인

의 방법은 어떨까요?

위에 [코멘트](https://github.com/woowacourse-teams/2024-haeng-dong/pull/47#discussion_r1685273551) 의 망쵸 답변처럼 `List<MemberAction>` 을 주고 받으면 정렬이 된건지 안된건지 역방향인지 기존 memberActions인지 새로 추가하려는 memberActions인지 알기 어려운 것 같아요. 

현재는 성능보다 가독성을 더 중요시하면 어떨까 합니다.

2024-07-20 14:31 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +        memberActions.sort(Comparator.comparing(MemberAction::getSequence));
```suggestion
        memberActions.sort(Comparator.comparing(MemberAction::getSequence).reversed());
```

2024-07-20 14:31 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +        return MemberActionStatus.IN != status;
```suggestion
        return actions.stream()
                .filter(action -> action.isSameName(name))
                .findFirst()
                .map(action -> action.isSameStatus(status))
                .orElse(MemberActionStatus.IN != status);
```

2024-07-20 14:32 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
> +    @Query("select m from MemberAction m where m.action.event = :event")
소문자로 결론 났습니다 땅땅땅

2024-07-20 14:44 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +                return action.isSameStatus(status);
```suggestion
    private boolean isInvalidStatus(List<MemberAction> memberActions, String memberName, MemberActionStatus memberActionStatus) {
        for (int i = memberActions.size() - 1; i >= 0; i--) {
            MemberAction memberAction = memberActions.get(i);
            if (memberAction.isSameName(memberName)) {
                return memberAction.isSameStatus(memberActionStatus);
            }
        }
        return MemberActionStatus.IN != memberActionStatus;
    }
```

이상 제안에 100퍼 동의합니다! 위는 이상의 제안을 모두 반영한 코드인데요. 추가로 `status` -> `memberActionStatus`를 제안해 봅니다. 

> 이외에도 코드 전반적으로 타입명과 변수명을 일치시키는 것은 어떤지 팀원 전체 의견을 들어보고 싶습니다.

일치하는 방향으로 작성하고, 예외 상황에서는 유도리 있게 작성하기 어떤가요?

2024-07-20 14:48 UTC, kunsanglee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +        return MemberActionStatus.IN != status;
isInvalidStauts 메서드의 매개변수로 받아온 인원 변동 이력인 List<MemberAction> 을 전부 순회하면서,
새로운 인원 변동 요청에 포함된 참여자의 이름과 같은 경우 마지막 변동 상태와 요청 상태를 비교하는 로직입니다.
단건 검증이 아니기 때문에 filter를 사용하는 것은 불가능한 상황입니다. 👍

2024-07-20 14:49 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/request/MemberActionsSaveAppRequest.java
> +}
c: DTO에 일급컬렉션을 적용하면 어떤 이점이 있을까요? 
presentation 단에서는 주고받는 json형태를 객체로 하기 위해 일급컬렉션을 사용했는데요. application단의 dto까지 일급컬렉션을 적용해야하는지 잘 모르겠습니다. 감싸고 푸는 번거로움만 늘어가는 것 같아요.

2024-07-20 14:52 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/MemberActionStatus.java
> +    }
r: 사용하지 않는 메소드는 지워주세요.

2024-07-20 14:55 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
r: 개행을 안해도 딱 120자입니다.

2024-07-20 15:01 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +    private void validateAction(List<MemberAction> memberActions, MemberActionSaveAppRequest action) {
```suggestion
    private void validateAction(MemberActionSaveAppRequest action, List<MemberAction> memberActions) {
```

`validateActions`와 컨벤션이 맞지 않아서 코멘트 남겨봅니다 :)

2024-07-20 15:08 UTC, 3Juhwan commented
오늘 이상과 페어프로그래밍하면서 고민한 부분과 저의 주장을 펼쳐 보겠습니다. 

c: sorting, reversed는 검증 로직을 위해 존재합니다. sorting, reversed은 검증 이후에 일어나는 MemberActions 생성 로직에는 불필요하고, 영향을 미치면 안됩니다. 이 근거로 검증 로직 하위로 sorting과 reversed 로직을 옮기는 것을 제안합니다. 

```java
public List<MemberAction> createMemberActions(
            MemberActionsSaveAppRequest request,
            List<MemberAction> memberActions,
            Action action
    ) {
        validateActions(request, memberActions);

        Long memberGroupId = memberGroupIdProvider.createGroupId();
        List<MemberAction> createdMemberActions = new ArrayList<>();
        List<MemberActionSaveAppRequest> actions = request.actions();
        for (MemberActionSaveAppRequest appRequest : actions) {
            MemberAction memberAction = appRequest.toMemberAction(action, memberGroupId);
            createdMemberActions.add(memberAction);
            action = action.next();
        }

        return createdMemberActions;
    }

    private void validateActions(MemberActionsSaveAppRequest request, List<MemberAction> memberActions) {
        List<MemberAction> reverseSortedMemberActions = memberActions.stream()
                .sorted(Comparator.comparing(MemberAction::getSequence).reversed())
                .toList();

        for (MemberActionSaveAppRequest action : request.actions()) {
            validateAction(reverseSortedMemberActions, action);
        }
    }
```

2024-07-20 15:13 UTC, kunsanglee commented on server/src/main/java/server/haengdong/application/request/MemberActionsSaveAppRequest.java
> +}
지금의 DTO 구조에서 얻을 수 있는 이점이라고 하면 JSON 요청 본문에 포함되는 데이터가 List<MemberActionSaveRequest> 이외에 추가된다면 쉽게 넣을 수 있다는 점이 있습니다. 저희가 논의했을 때는 요청 본문을 List로 받게되면 요청 데이터가 추가되거나 변경될 때 확장성이 떨어진다고 생각하여 한 번 더 감싸서 받기로 결정했었던 것 같아요. 저도 팀원들과 함께 다시 논의해볼 필요는 있다고 생각합니다.

2024-07-20 15:29 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +        return MemberActionStatus.IN != status;
filter 사용이 불가능하다고 하셨는데, 이해하지 못했습니다. 

위 코드는 actions stream에서 findFirst를 사용했기 때문에 순차 스트림이고 첫 번째 원소가 반환될 거라 생각합니다. 
기존 로직은 if 조건식에 따라 동일한 이름을 가진 원소를 찾으면 if 문 내부로 들어가서 결과가 바로 return 되는 구조입니다. 

두 로직 모두 동일한 결과를 반환할 것으로 예상되고, 로컬에서 수정했을 때에 테스트 코드가 모두 통과합니다. 
좀더 자세한 설명 부탁드려도 될까요? :)

2024-07-20 15:39 UTC, kunsanglee commented
> 오늘 이상과 페어프로그래밍하면서 고민한 부분과 저의 주장을 펼쳐 보겠습니다. 모두의 의견을 기다립니다!
> 
> 다음은 기존에 논의된 코드입니다.
> 
> ```java
> public List<MemberAction> createMemberActions(
>             MemberActionsSaveAppRequest request,
>             List<MemberAction> memberActions,
>             Action action
> ) {
>    memberActions.sort(Comparator.comparing(MemberAction::getSequence)).reversed();
> 
> ...
> 
> }
> ```
> 
> c: sorting, reversed는 검증 로직을 위해 존재합니다. sorting, reversed은 검증 이후에 일어나는 MemberActions 생성 로직에는 불필요하고, 영향을 미치면 안됩니다. 이 근거로 검증 로직 하위로 sorting과 reversed 로직을 옮기는 것을 제안합니다.
> 
> ```java
> public List<MemberAction> createMemberActions(
>             MemberActionsSaveAppRequest request,
>             List<MemberAction> memberActions,
>             Action action
> ) {
>     validateActions(request, memberActions);
> 
>     Long memberGroupId = memberGroupIdProvider.createGroupId();
>     List<MemberAction> createdMemberActions = new ArrayList<>();
>     List<MemberActionSaveAppRequest> actions = request.actions();
>     for (MemberActionSaveAppRequest appRequest : actions) {
>         MemberAction memberAction = appRequest.toMemberAction(action, memberGroupId);
>         createdMemberActions.add(memberAction);
>         action = action.next();
>     }
> 
>     return createdMemberActions;
> }
> 
> private void validateActions(MemberActionsSaveAppRequest request, List<MemberAction> memberActions) {
>     // memberActions를 기반으로 Stream을 만들어 정렬함으로 기존 데이터에 영향을 미치지 않습니다. 
>     List<MemberAction> reverseSortedMemberActions = memberActions.stream()
>             .sorted(Comparator.comparing(MemberAction::getSequence).reversed())
>             .toList();
> 
>     for (MemberActionSaveAppRequest action : request.actions()) {
>         validateAction(reverseSortedMemberActions, action);
>     }
>  }
> ```
> 
> 위처럼 수정하면 하위 메서드인 `isInvalidStatus`를 같이 수정할 수 있습니다.
> 
> ```java
> private boolean isInvalidStatus(List<MemberAction> memberActions, String memberName, MemberActionStatus memberActionStatus) {
>     for (MemberAction memberAction : memberActions) {
>         if (memberAction.isSameName(memberName)) {
>             return memberAction.isSameStatus(memberActionStatus);
>         }
>     }
>     return MemberActionStatus.IN != memberActionStatus;
> }
> ```

인원 변동 이력인 List<MemberAction>를 정렬하고 새로운 인원 변동 요청과 비교하여 수행하는 검증 로직이 
createMemberActions 메서드의 생성 로직에 영향을 주지 않는다면, 검증 로직과 생성 로직을 분리하는 것도 괜찮다고 생각해요.

그리고 repository에서 조회해온 List<MemberAction>와 MemberActionsSaveAppRequest을 검증하는 것은 새로운 검증 객체에서 하거나 MemberActionService 에서 하는 것이 오히려 자연스러울 수 있을 것 같아요. 조회한 이력과 요청을 비교한 결과 MemberActionFactory의 createMemberActions 메서드를 수행할 수 있냐 없냐를 판단하기 때문입니다. 

하지만 이런 흐름으로 가더라도 AppRequest가 MemberActionFactory로 들어가게 되어 순수 도메인 객체가 되지는 못하겠네요.

2024-07-20 15:40 UTC, kunsanglee commented on server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
> +class MemberActionFactoryTest {
createMemberActions 메서드 수행 결과로 반환되는 List<MemberAction> 의 값을 검증하는 테스트를 추가했습니다. 👍

2024-07-20 15:41 UTC, kunsanglee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +                return action.isSameStatus(status);
너무 좋습니다 💯

2024-07-20 15:47 UTC, kunsanglee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +        return MemberActionStatus.IN != status;
for문으로 순회하는 시작 부분의 코드를 actions.stream()으로 전부 바꾸는 것으로 잘못 봤네요.. 
백호가 말씀해주신대로 filter를 사용하고 인원 변동 요청만큼 해당 로직을 반복하면 같은 결과가 나오는게 맞습니다.

2024-07-20 16:17 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +    ) {
c: memberActionsSaveRequest에 중복된 member가 있는 것도 검증되었나요?
ex) ("토다리", "IN"), ("토다리", "IN") 2개 요청

2024-07-21 02:23 UTC, khabh commented on server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
> +    @DisplayName("액션 ID를 기준으로 정렬한 상태로 새로운 멤버 액션 요청을 검증한다.")
c: unorderedMemberActions를 인자로 넣는 게 테스트의 핵심이었군요, 이상의 설명을 듣고 나니 지정된 테스트 이름이 납득되네요. 다만 현재 이름은 createMemberActions 코드 내 정렬 기준을 액션 ID라고 판단하게 될 여지가 있는 것 같아요. sequence라는 정렬 기준을 테스트 명에 포함해 보는 건 어떨까요?

2024-07-21 02:26 UTC, khabh commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +                return action.isSameStatus(status);
다들 간결하고 짧은 네이밍을 선호하는 것 같아서 굳이 언급은 안 했는데, 사실 저는 타입명과 변수명을 일치시키는 것을 매우매우 선호합니다.

2024-07-21 02:42 UTC, khabh commented
> 인원 변동 이력인 List를 정렬하고 새로운 인원 변동 요청과 비교하여 수행하는 검증 로직이
createMemberActions 메서드의 생성 로직에 영향을 주지 않는다면, 검증 로직과 생성 로직을 분리하는 것도 괜찮다고 생각해요.
>
> 그리고 repository에서 조회해온 List와 MemberActionsSaveAppRequest을 검증하는 것은 새로운 검증 객체에서 하거나 MemberActionService 에서 하는 것이 오히려 자연스러울 수 있을 것 같아요. 조회한 이력과 요청을 비교한 결과 MemberActionFactory의 createMemberActions 메서드를 수행할 수 있냐 없냐를 판단하기 때문입니다.
>
> 하지만 이런 흐름으로 가더라도 AppRequest가 MemberActionFactory로 들어가게 되어 순수 도메인 객체가 되지는 못하겠네요.

우선 망쵸가 이전 코멘트에 남긴대로 sorting, reversed을 검증 로직으로 옮기는 것은 좋다고 생각합니다. 추가적으로 저는 MemberActionFactory와 MemberActionService에 대한 예외 테스트가 중복된다는 느낌을 받아서, MemberService에서 검증을 수행하는 것에도 찬성합니다~

2024-07-21 06:09 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +    ) {
추가했습니다 :)

2024-07-21 06:14 UTC, Arachneee approved these changes
코멘트 잘 반영해주셨네요~
수고하셨어요!

2024-07-21 06:14 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/MemberActionFactory.java
> +    }
c: 메소드 순서 바꿔주시면 좋을 것 같아요~

2024-07-21 06:14 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/Action.java
> +        return new Action(event, sequence + 1);
c: 1도 매직넘버로 추출하는 것은 어떨까요?

2024-07-21 06:17 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/domain/Action.java
> +        return new Action(event, sequence + 1);
이 부분은 #45 에서 머지된 내용과 충돌날 예정으로, 충돌 해결하는 시점에 반영하면 될 것 같아요!

2024-07-21 06:20 UTC, khabh approved these changes

2024-07-21 06:32 UTC, merged