Feature/#546 part2
woowacourse-teams/2024-haeng-dong pull request #559
Opened 2024-09-14 12:53 UTC by 3Juhwan

## 구현 사항
- 행사 정보 수정 API `구현`, `테스트`
- 행사 전체 인원 조회 API `테스트`
- 현재 참여 인원 조회 API `테스트`

## 🫡 참고사항
- Member 조회 API에 Member.id가 필요합니다. 
- 현재 id를 할당할 방법이 없습니다. 이에 대한 논의가 필요합니다. 
- 현재는 관련 레독 테스트를 주석과 null 처리해두었습니다.

2024-09-14 13:02 UTC, Arachneee requested changes
안녕하세요 망쵸!
고생하셨어요 👍 
코멘트 확인 부탁해요!

2024-09-14 13:02 UTC, Arachneee commented on server/src/test/java/server/haengdong/application/MemberServiceTest.java
> +    }
지출이 있는 경우와 없는 경우로 나눠서 테스트하면 될 것 같아요.

2024-09-14 13:02 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/request/EventUpdateAppRequest.java
> +    }
dto에 로직이 있는 이유가 있나요?

2024-09-14 13:07 UTC, Arachneee commented
> Member 조회 API에 Member.id가 필요합니다.
현재 id를 할당할 방법이 없습니다. 이에 대한 논의가 필요합니다.

무슨 말인지 잘 모르겠어요. member의 id는 항상 존재하지 않나요?

2024-09-14 13:10 UTC, 3Juhwan commented
질문이 부실했네요 미안합니다. 

컨트롤러 테스트와 레독 테스트에서 사용하는 Fixture.Member는 id가 세팅되어 있지 않습니다. 따라서 기존의 Fixture는 사용하기 어렵습니다. 
id가 세팅된 Member를 만들기에 현재 도메인에 생성자가 없습니다. 테스트를 위해 생성자를 만드는 것이 괜찮을지 팀에게 물어봅니다.

2024-09-14 13:22 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/docs/MemberControllerDocsTest.java
> +                .andExpect(jsonPath("$.members[2].isDeposited").value(member3.isDeposited()))
이 레독 테스트는 Member.id를 반환하는 API로 테스트가 필요합니다. 
해당 주석을 풀면 `"$.members[0].id" is null`로 에러가 발생합니다. 
원인은 Fixture.Member에 id를 세팅하지 않기 때문입니다. 

문제를 해결하기 위해 id가 세팅된 Member가 필요합니다. 현재 Member에 id를 세팅할 수 있는 생성자가 없는 상태입니다. 
테스트만을 위한 생성자를 열어도 될까요?

2024-09-14 13:26 UTC, Arachneee commented on server/src/test/java/server/haengdong/docs/MemberControllerDocsTest.java
> +        );
어짜피 모킹하는데 Member객체 안쓰고 dto를 만들면 되는 것 아닌가요?

2024-09-14 13:33 UTC, khabh commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
프론트에서 선택할 수 있는 은행이 제한되어 있으니,  bankName은 enum으로 관리해도 좋을 것 같아요

[은목](https://github.com/woowacourse-teams/2024-haeng-dong/blob/7038777034dd70ba3917b343645c1ed545029acc/client%2Fsrc%2Fconstants%2Fbank.ts)

2024-09-14 13:33 UTC, khabh commented on server/src/test/java/server/haengdong/application/EventServiceTest.java
> +        EventUpdateAppRequest eventUpdateAppRequest = new EventUpdateAppRequest(null, "망쵸뱅크", "12345678");
망쵸뱅크

2024-09-14 13:35 UTC, 3Juhwan commented on server/src/test/java/server/haengdong/docs/MemberControllerDocsTest.java
> +        );
아 그러네요 👍 
다른 코드와 비슷한 스타일로 작성하려다 보니 매몰됐었네요

2024-09-14 13:49 UTC, khabh requested changes
실수로 중간에 comment를 눌러버려서 냅다 리뷰 두 번 남긴 사람이 되어버렸네요 🥲
변경 사항 꽤 많았는데도 테스트 꼼꼼하게 잘 작성되어 있네요 👍 
고생했어요 삼망쵸

2024-09-14 13:49 UTC, khabh commented on server/src/main/java/server/haengdong/application/EventService.java
> +        }
변경 사항으로 들어오는 행사 이름이랑 계좌에 대해 EventService 내에 isEventNameExist(request), isAccountExist(request)와 같은 메서드를 추가하거나 event 내에서 해당 문자열에 대한 업데이트 여부를 판단해 주는 게 더 좋을 것 같아요 👀

2024-09-14 13:49 UTC, khabh commented on server/src/main/java/server/haengdong/application/MemberService.java
> +    public List<LastBillMemberAppResponse> getCurrentMembers(String token) {
반환 타입 `List<LastBillMemberAppResponse>`와 getCurrentMembers라는 메서드 이름이 매칭이 잘 안 되는 것 같아요. 그냥 MemberAppResponse를 반환해 주는 건 어떨까요?

2024-09-14 13:57 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
지금 구조에서 Enum으로 관리하면 할 수 있는 건 올바른 은행 이름인지 검증하는 것 같아요. 그 외에는 없다고 생각해요. 
이점이 이것 뿐이라면, 은행 목록의 변경 및 추가 상황에 대응하기 쉬운 건 지금처럼 String으로 관리하는 거라 생각해요. 

다른 분들은 어떻게 생각하시나요?

2024-09-14 14:00 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/MemberService.java
> +    public List<LastBillMemberAppResponse> getCurrentMembers(String token) {
관련된 네이밍 수정하고 있었는데, 놓쳤네요. 찾아주셔서 감사해요 👍

2024-09-14 14:29 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
은행 목록의 변경 및 추가 상황에 enum만 추가, 변경하면 되니 대응하기 더 쉽지 않을까요?

2024-09-14 14:35 UTC, kunsanglee commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
enum으로 은행 이름과 계좌 자릿수를 정규식으로 관리하면 어떨까 했는데,
찾아보니 은행별 계좌 자릿수 종류가 1개가 아니더군요.
게다가 지금 우리 코드에서 은행별로 분기를 나누는 것도 아니니 일단은 String으로 관리해도 문제 없을 것 같습니다.

2024-09-14 14:48 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
@Arachneee 

enum으로 관리하면 쉬운 건 사실이에요. 하지만 단순히 은행 목록이 변경되더라도 코드를 수정하고 재빌드 및 배포까지 해야 해요. 
아직은 String으로 관리해도 문제될 게 없다고 생각해요. 그대로 가도 괜찮을까요?

2024-09-14 15:13 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/application/request/EventUpdateAppRequest.java
> +    }
dto에서 하는 게 자연스러워 보입니다.

2024-09-14 15:25 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
은행정보는 우리 서비스의 사용자들이 어떤 은행을 많이 사용하는지 볼 수 있는 중요한 정보라고 생각해요. 
데이터 분석을 통해 우리 서비스의 방향성을 결정할 수 도 있죠.

따라서 별도의 컬럼으로 관리하는 것이 더 좋다고 생각합니다.
현시점에서는 정제되지 않은 데이터를 그대로 넣는 것이 큰 문제는 없겠지만 나중에 컬럼으로 분리하게 된다면 데이터 마이그레이션을 할때 큰 어려움이 있을 것으로 예상됩니다. 
무엇보다 은행이름 검증도 없기 때문이죠. "국민", "KB", "KB 국민" 이런 다양한 데이터들을 마이그레이션하기 어렵다고 생각합니다.

2024-09-14 15:33 UTC, Arachneee commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
은행 목록은 변경이 적을 뿐더러 재배포를 하고 싶지 않아서 데이터를 말아넣는 것이 좋은 선택인지 잘 모르겠습니다. 
은행이 추가되는 주기와 백엔드 재배포 주기를 비교해보면 백엔드 재배포 주기가 훨씬 짧다고 생각합니다.

2024-09-14 16:22 UTC, 3Juhwan commented on server/src/main/java/server/haengdong/domain/event/Event.java
> +    public void changeAccount(String bankName, String accountNumber) {
설득력 있네요 👍 
`서비스 방향성`, `데이터 마이그레이션`, `변경 가능성 낮음`
물론,,, 솔직하게 우리 서비스에 해당되는 근거인지는 공감하기 어려운 거 같아요. 
`변경 가능성 낮음`은 굉장히 타당하네요.

2024-09-14 16:55 UTC, Arachneee approved these changes

2024-09-15 00:34 UTC, khabh approved these changes

2024-09-15 00:36 UTC, merged