[BE] PR 후 push 시 CI가 돌지 않는 버그 수정
woowacourse-teams/2024-haeng-dong pull request #56
Opened 2024-07-20 00:20 UTC by Arachneee

## issue
- close #55

## 구현 사항
트리거 조건에 types를 추가했습니다.

## 중점적으로 리뷰받고 싶은 부분(선택)
어떤 부분을 중점으로 리뷰했으면 좋겠는지 작성해주세요.

## 논의하고 싶은 부분(선택)
논의하고 싶은 부분이 있다면 작성해주세요.

## 🫡 참고사항

2024-07-20 00:26 UTC, kunsanglee approved these changes

2024-07-20 01:02 UTC, 3Juhwan requested changes

2024-07-20 01:02 UTC, 3Juhwan commented on .github/workflows/backend-pull-request.yml
> +    branches: [ "main", "develop", "feature/#55" ]
r: 특정 브랜치를 명시하면 안 될 것 같아요. 확인 부탁드려요! pr 날린 브랜치에 추가 작업을 할 때에는 온전한 작업물 단위로 푸쉬해야 할 것 같네요 :) 물론 ci 작업은 어쩔 수 없지만요

2024-07-20 15:56 UTC, Arachneee commented on .github/workflows/backend-pull-request.yml
> +    branches: [ "main", "develop", "feature/#55" ]
테스트 용으로 추가했었어요.

[pr test](https://github.com/woowacourse-teams/2024-haeng-dong/pull/57)
에서 어떻게 나오는지 한번 확인해주시고 approve 해주세요.

`"feature/#55"` 는 삭제해서 merge할게요.

2024-07-21 02:49 UTC, 3Juhwan approved these changes
#55 확인했습니다. 고생하셨어요. 
pr.yml에 추가한 스크립트에 대한 간단한 설명을 첨부해 주시면 감사할 것 같아요.

2024-07-21 02:49 UTC, 3Juhwan commented on .github/workflows/backend-pull-request.yml
> +    branches: [ "main", "develop", "feature/#55" ]
오호,,, 좋네요  👍👍👍 
얼른 새 pr을 날려서 확인해 보고 싶네요. 고생하셨습니다.

2024-07-21 04:22 UTC, merged