[FE] 입금 상태를 변경하고 '수정완료' 버튼 클릭 시, 중복 이름 버그 발생
woowacourse-teams/2024-haeng-dong pull request #611
Opened 2024-09-25 00:16 UTC by soi-ha

## issue
- close #600

## 구현 사항

# 🚨 백엔드 api 수정 이후, merge 진행

### 버그 발생 상황
입금 상태만을 변경하고 '수정완료' 버튼을 클릭하면 "중복 이름입니다" 버그가 발생했습니다.
이에 대한 문제는 api 구조의 문제로 결론이 났습니다. 따라서 해당 문제의 해결은 백엔드의 수정 후에 정확히 확인해봐야 할 것 같습니다.

### 또 다른 버그 발생 상황 사전 방지
전체 참여자 delete,put 요청 mutate대신 mutateAsync를 사용하여 요청 순서 보장했습니다.
순서를 보장하지 않는다면 delete 요청 전에 put 요청이 먼저 갈 수 있다는 문제가 존재합니다. 
delete 요청 전, put 요청이 가는 것이 왜 문제냐? 생각하실 수 있습니다. put 요청은 delete가 요청이 된 것을 기반으로 데이터가 존재합니다. 따라서 delete 요청이 무조건 선행 되어야 put 요청을 전송할 수 있습니다.

## 🫡 참고사항

2024-09-25 00:20 UTC, jinhokim98 requested changes
mutateAsync로 바꿔주신 내용 확인했습니다.
하지만 mutateAsync로 내보내줬다고 해서 순서가 보장되지 않고 mutateAsync 호출처에서 await을 사용해줘야 delete 요청을 기다린 후에 put요청을 보낼 수 있습니다.
이것 때문에 request change 드립니다.

2024-09-25 01:35 UTC, pakxe approved these changes
좋은 해결책인 것 같아요~!!

2024-09-25 01:35 UTC, pakxe commented on client/src/hooks/queries/member/useRequestPutMembers.ts
> +  return {putMember: mutateAsync, ...rest};
👍 👍 👍

2024-09-25 23:02 UTC, Todari approved these changes
고생햇서요~!~!

2024-09-25 23:02 UTC, Todari commented on client/src/hooks/queries/member/useRequestDeleteMember.ts
> +  return {deleteMember: mutateAsync, ...rest};
우리가 지금 사용하고 있는 react-query hook들이 다 같은 이름 형식으로 내보내고 잇는데,
deleteMember가 mutateAsync를 내보낸 거라는걸 알기 위해서는
deteleMemberAsync와 같은 식으로 내보내줘도 좋을 것 같아요~!

2024-09-26 00:35 UTC, jinhokim98 approved these changes
이후 pr에서 잘 적용해주셔서 approve로 바꿀게요!

2024-09-26 01:22 UTC, soi-ha commented on client/src/hooks/queries/member/useRequestDeleteMember.ts
> +  return {deleteMember: mutateAsync, ...rest};
오 ~ 알겠습니댜! 좋은 것 같아요

2024-09-26 06:06 UTC, merged