[FE] TopNav 버튼 강조 및 계좌번호 접근 관련
woowacourse-teams/2024-haeng-dong pull request #697
Opened 2024-10-03 13:25 UTC by jinhokim98

## issue
- close #680 

## 구현 의도
로그인 화면으로 들어와도 TopNav 관리가 활성화 되어있어야 한다고 생각했습니다.
그래야 내가 관리 페이지로 들어와서 로그인을 하라는거구나~ 인지를 할 수 있다고 생각했습니다.

## 구현 사항

### 로그인 페이지 제거, AuthGate 추가
기존의 /event/eventId/login 페이지를 제거했습니다.  그래서 관리 페이지의 구조를 조건부 랜더링으로 바꿨습니다.  
로그인이 됐을 땐 기존의 관리를 보여주고, 그러지 않을 땐 로그인 페이지를 보여주도록 했습니다.

조건부 랜더링을 제어해주는 것이 AuthGate입니다. AuthGate에서 토큰이 있는지를 확인한 후 조건에 맞는 랜더링을 해줍니다.
```tsx
<AuthGate fallback={<EventLoginPage />}>
  <AdminPage />
</AuthGate>

### auth store 추가
관리자 상태를 전역으로 관리하도록 변경했습니다. 
전의 방식은 단순 url만 비교해서 /admin이 true일 때 admin으로 판단해서 true로 주었다면
지금의 방식은 실제 토큰이 있는 지를 판단하도록 변경했습니다.
바뀐 방식의 상태를 전역으로 관리하지 않으면 여러 곳에서 사용할 수 없다고 판단해 추가했습니다.

### 계좌번호가 등록되지 않았을 때 페이지 접근 관련
어제 얘기하면서 "홈"에서 초대하기를 눌렀을 때 계좌번호 입력 페이지로 넘어가는 것이 부자연스럽다는 이야기가 나왔습니다. 하지만 생각해보니 관리자가 저 화면을 보는 것은 문제 없다고 생각했어요. 어떻게 보면 당연히 그렇게 해야 한다고 생각합니다.

계좌번호를 등록해야 송금 기능을 이용할 수 있기 때문이며, "홈"에서든 "관리"에서든 초대하려고 할 때 계좌번호를 먼저 등록하도록 유도하는 것은 잘못되지 않았다고 생각합니다.

하지만 정산자가 아닌 참여자가 이 링크를 확인할 때는 문제가 생깁니다. 
그래서 참여자가 계좌번호가 입력되지 않은 링크를 찾아 들어와 초대를 할 경우 아래 화면처럼 토스트를 보여주도록 했어요.

(좋은 UX인지는 모르겠어요;;;)
![image](https://github.com/user-attachments/assets/2a7524d0-a8f4-4592-97f7-1a391c96fd6c)

정상적인 이용자라면
1. 정산자가 초대 버튼 클릭
2. 계좌번호 입력
3. 정산자가 다시 초대 버튼 클릭 후 공유 완료
4. 참여자가 링크로 들어와 초대 버튼 클릭 (아무 이상없음)

흐름대로 갈 것 같은데, 비정상적으로 참여자가 미리 들어와 버릴 경우 저렇게 보여주는 것이 최선이라고 생각했어요..
준비가 안 됐는데 초대를 해버리면 송금 기능을 못 사용하니;;;

## 논의하고 싶은 부분(선택)
위 토스트에 대해 논의해봐요

## 🫡 참고사항

2024-10-03 13:47 UTC, Todari requested changes
휴일에도 열일하는 쿠키...
한가지 인지하고 있던 사용자 경험 개선 사항중에 하나가, 로그인 페이지에서 "관리" 탭을 클릭하면 `/login` 에서 `/admin`으로 계속 넘어가면서 화면이 계속 깜빡이는 현상이 있었어요.
이 부분을 공유하려고 했는데, 쿠키가 이 부분을 깔끔하게 리팩토링해내면서 함께 해결이 됐네요!!!
역시 갓갓쿠키
`ShareEventButton`과 `EventPageLayout`의 역할 분담에 대해서 고민거리를 comment 달았는데, 우선 변경요청을 해놓을게요.
변경을 해라!!! 가 아니라 내일 같이 얘기해 보면 좋을 것 같아요 :)

그럼 남은 휴일 잘 보내고 내일 봐요 쿠키 ~!

2024-10-03 13:47 UTC, Todari commented on client/src/pages/EventPage/AuthGate/index.tsx
> +const AuthGate = ({children, fallback}: AuthGateProps) => {
아니 여기 원래 달았던 댓글 날아가고 왜 이게 들어가있는거야... 하... 길게썼는데

2024-10-03 14:06 UTC, jinhokim98 commented on client/src/components/ShareEventButton/ShareEventButton.tsx
> +  eventPageOutletContext: EventPageContextProps;
전역상태로 관리한만큼 isAdmin 정보를 context에 담지 않아도 되겠네요!

이 부분 내일 개선해볼게유

2024-10-03 14:09 UTC, jinhokim98 commented on client/src/pages/EventPage/AuthGate/index.tsx
> +const AuthGate = ({children, fallback}: AuthGateProps) => {
음.. 확실히 맞는 말이네요

다른 곳에서도 버튼을 트리거 역할로 쓰고 다른 기능들은 외부에서 넣어주니깐
외부에서 onClick으로 넣어서 줘도 좋을 것 같아요

하나하나 개선점을 찾아나가는 과정 좋습니다. 내일 이야기해봅시다!

2024-10-07 05:06 UTC, soi-ha approved these changes
저번에 놓친 부분 수정해줘서 고마워요!!!!!!

2024-10-07 05:06 UTC, soi-ha commented on client/src/router.tsx
> +              </AuthGate>
오홍~ 👍

2024-10-07 05:06 UTC, soi-ha commented on client/src/store/authStore.ts
> +}));
죽어있던 zustand를 살린 쿠키

2024-10-07 07:19 UTC, jinhokim98 commented on client/src/components/ShareEventButton/ShareEventButton.tsx
> +      toast.error('잠깐! 정산을 초대하기 전에\n계좌를 등록해주세요', {
이 부분 웨디가 파악했고 이슈가 있습니다!

2024-10-09 11:17 UTC, pakxe commented on client/src/components/ShareEventButton/ShareEventButton.tsx
> +      toast.error('잠깐! 정산을 초대하기 전에\n계좌를 등록해주세요', {
pr올려두었습니다아 ~!

2024-10-10 06:54 UTC, Todari approved these changes
변경된것 잘 확인했어요 그저 대 쿠 키

2024-10-10 06:54 UTC, merged