[FE] 지출 내역 추가 플로우에서 참여 인원의 토큰의 x버튼에 낭독기 커서가 가도록 함
woowacourse-teams/2024-haeng-dong pull request #759
Opened 2024-10-16 13:51 UTC by pakxe

## issue
- close #747 

## 개선 전 / 후
🔻 개선 전

https://github.com/user-attachments/assets/4915f133-737b-44c7-a2a5-9296b136c5bd

🔻 개선 후

https://github.com/user-attachments/assets/74bc0f59-519c-49f2-a457-c62daef6264e

## 구현 목적
현재 낭독기 사용 시 지출 내역 추가 플로우에서 참여 인원의 토큰(ChipButton)의 x버튼에 낭독기 커서가 가지 않습니다. 
따라서 낭독기 사용자는 참여 인원을 삭제할 수 없는 상황인데요. 이를 위해 x버튼에 낭독기 커서가 갈 수 있도록 구현합니다.

## 구현 방법
커서가 가지 않는 이유는 x버튼이 단순한 'div'태그로만 그려지고 있기 때문입니다. x버튼은 말 그대로 '버튼'이기 때문에 button태그가 사용되어야 낭독기 사용자들에게 쉽게 화면을 읽어줄 수 있어요.

x버튼은 `Icon`이라는 컴포넌트가 사용되고 있는데요. Icon이면서 버튼이기도 해야하는 경우 프로젝트 내에선 `IconButton`이라는 컴포넌트를 감싸 사용하는 것으로 확인되었습니다.

따라서 IconButton컴포넌트로 Icon컴포넌트를 감싸주었어요.
```jsx
<IconButton variants="none">
  <Icon iconType="inputDelete" onClick={onClick} />
</IconButton>
```

이렇게 바꾸면 바라던대로 커서는 향하지만 "버튼"이라고만 읽히게 됩니다. 
따라서 해당 버튼이 어떤 버튼인지 의미를 알려주기 위해 아이콘 이미지들에 aria-label을 사용해주었어요.
하지만 이름과 사용처를 확인 후 의미를 추측해서 적은것 뿐, 더 명확하고 좋은 표현이 있을 수 있기 때문에 더 좋은 라벨이 있다면 커멘트 부탁드립니다 ~!
```jsx
export const ICON = {
  inputDelete: <InputDelete aria-label="지우기" />,
  rightChevron: <RightChevron aria-label="더보기" />,
  search: <Search aria-label="검색" />,
  error: <Error aria-label="오류" />,
  confirm: <Confirm aria-label="확인" />,
  trash: <Trash aria-label="삭제" />,
  trashMini: <TrashMini aria-label="삭제" />,
  check: <Check aria-label="선택" />,
  x: <X aria-label="x" />,
  pencilMini: <PencilMini aria-label="수정" />,
  toss: <img src={Toss} width="16" height="16" alt="toss icon" />,
  meatballs: <Meatballs aria-label="메뉴" />,
  editPencil: <EditPencil aria-label="수정" />,
  heundeut: <img src={`${process.env.IMAGE_URL}/heundeut.svg`} aria-label="행동대장 로고" />,
  photoButton: <PhotoButton aria-label="사진" />,
} as const;
```

alt가 아닌 aria-label을 사용한 이유는 svg파일에는 alt 속성이 없어서 그렇습니다. 
중간에 png가 있긴 한데 한개 뿐입니다. 그래서 오히려 png만 alt로 바꾸는게 의아함을 주지 않을까 싶어 aria-label로 통일했는데요. png가 더 생길 것을 생각하여 alt를 사용하는게 좋을 것 같다~ 라면 바꾸겠습니다!

## 참고
스토리북의 언어 설정을 바꾸지 않은 이유는, 버튼을.. 붜턴~ 이라고 읽는 것 말고는 차이가 없어서 그냥 그대로 녹화해보았어요.
그래도 스토리북에 한국어 설정하는 방법을 알려주어서 고맙습니다 쿳키~

2024-10-16 15:01 UTC, soi-ha requested changes
웨디가 작성해준 코드와 PR 내용 잘 읽어봤습니다! 개선 후 영상을 보니 이제는 스크린리더로 인원 삭제도 가능해졌네용 👍

다만, 논의해보고 싶은 부분이 있어서 RC했습니당! 확인해보시고 말씀해주세용~

2024-10-16 15:18 UTC, pakxe commented on client/src/components/Design/components/Icon/Icon.tsx
> +export const ICON = {
아하 확실히 그럴 수 있겠네요. 소하 의견처럼 고려해도 좋을 것 같아요.

제가 이미지에 라벨을 단 이유는 Icon컴포넌트를 사용하는 곳에서 라벨을 매번 부착하는 수고를 덜기 위함이었습니다. 이미지에 달면 매번 라벨을 써줄 필요가 없어지니까요. 

그리고 생각해보니 Icon에 따라 라벨이 나뉘는게 아니라, x버튼이어도 어떤 닫기 버튼인지 이름이 다를 수 있을 것 같아 매번 라벨을 사용하는 곳에서 지정해주는게 맞지 않을까 싶기도 해요.

그래서 위 사항들을 고려해 제가 생각한 방법은 ICON에 적용한 모든 라벨을 제거하고 그냥 라벨을 사용해야하는 사용처에서 IconButton에 라벨을 달아주는 것이 어떠한가.. 입니다! 어떤가요?!

2024-10-16 15:19 UTC, pakxe commented on client/src/components/Design/components/ChipButton/ChipButton.tsx
> +      </IconButton>
그냥 IconButton으로만 감싸면 해결되었어서 이 부분을 놓쳤군요..!! 바로 반영했습니다~!!

2024-10-17 01:44 UTC, Todari approved these changes
꼼꼼쓰 웨디의 코드 잘 보고 갑니당~!~!
결국 사용처에서 어떻게 사용하냐가 문제였네요 :)

2024-10-17 01:44 UTC, Todari commented on client/src/components/Design/components/Icon/Icon.tsx
> +export const ICON = {
소하 의견에 동의합니다~!~! 두분의 생산적인 토론 보기 좋네요 껄껄
저도 코드를 처음 보고 든 생각이, `IconButton`을 사용하는 사용처에서 label을 attribute로 넘겨주는게 좋을 것 같아용

2024-10-17 01:44 UTC, Todari commented on client/src/components/Design/components/Icon/Icon.type.ts
> +export type IconType = keyof typeof ICON;
:rocket::rocket::rocket::rocket::rocket:

2024-10-17 01:44 UTC, Todari commented on client/src/components/Design/components/IconButton/IconButton.tsx
>        {children}
`IconButtonProps` 에 이미 `React.ComponentProps<'button'>`을 prop으로 받고 있어서,
현재에도 사용처에서 `aria-label=~~~`과 같은 속성을 넘겨줄 수 있을거에요.
사용처에서 사용만 한다면 해결되는 문제일거라고 보여지네요!

2024-10-17 01:55 UTC, pakxe commented on client/src/components/Design/components/IconButton/IconButton.tsx
>        {children}
맞아요! 일단 제가 의미를 확인할 수 있는 IconButton에 모두 라벨을 달아볼게요!~!

2024-10-17 02:05 UTC, jinhokim98 approved these changes
다른 프엔분들이 너무 코멘트를 잘 달아줘서 (든든) 저는 approve할게요!
고생했습니당

2024-10-17 02:05 UTC, jinhokim98 commented on client/src/components/Design/components/Icon/Icon.tsx
> +export const ICON = {
저도 동의합니다! 같은 아이콘이어도 다른 aria-label을 주는 상황이 생길 수도 있으니깐요!

2024-10-17 02:05 UTC, jinhokim98 commented on client/src/components/Design/components/Icon/Icon.type.ts
> +export type IconType = keyof typeof ICON;
와 이거 매번 추가해주기 귀찮았는데~~ 너무 좋아요

2024-10-17 02:06 UTC, pakxe commented
피드백 주신 내용을 반영하여 코드를 수정해보았습니다! 

자세한 수정 내용은 pr본문에 연장하여 작성해두었으니 확인 부탁드려요~~!

2024-10-17 02:17 UTC, Todari commented on client/src/components/Design/components/IconButton/IconButton.tsx
>        {children}
고마워요 대 웨디~!

2024-10-17 02:20 UTC, Todari approved these changes
사용되는 곳들에서 꼼꼼하게 aria-label을 달아 주셨네요!
섬세퀸 웨디답게 다들 적절하고 너무 좋은 문구로 달아주신 것 같아요 :)
빠른 반영 감사합니다 고생 많았어요!!!

2024-10-17 02:20 UTC, Todari commented on client/src/pages/EventPage/AdminPage/EventMember.tsx
> +          aria-label="인원 삭제"
:+1:

2024-10-17 02:20 UTC, Todari commented on client/src/pages/MainPage/Nav/Nav.tsx
> +          <IconButton variants="none" aria-label="행동대장 로고">
:+1:

2024-10-17 02:20 UTC, Todari commented on client/src/components/Design/components/Input/Input.tsx
> +            <IconButton tabIndex={-1} variants="none" onMouseDown={onDelete} aria-label="입력 내용 모두 지우기">
:+1:

2024-10-17 02:20 UTC, Todari commented on client/src/components/Design/components/Dropdown/MeatballBase.tsx
> +      <IconButton variants="none" onClick={() => setIsOpen(true)} aria-label="더보기">
:+1:

2024-10-17 04:29 UTC, soi-ha approved these changes
반영해준거 잘 봤어요 웨디! 빠르게 반영해주시고.. 사용하지 않는 파일 제거까지 아주 굳입니댜!!

2024-10-17 04:29 UTC, soi-ha commented on client/src/components/Design/components/Banner/Banner.tsx
> +          onClick={onDelete}
반영 최고에용!

2024-10-17 04:29 UTC, soi-ha commented on client/src/components/Design/components/ChipButton/ChipButton.tsx
> +      </IconButton>
👍

2024-10-17 06:29 UTC, merged