feat: 액션 이력 조회 기능 구현
woowacourse-teams/2024-haeng-dong pull request #76
Opened 2024-07-23 04:15 UTC by kunsanglee

## issue
- close #20 

## 구현 사항
- 토큰으로 이벤트를 조회한다.
- 해당 이벤트에 속한 지출 내역과, 인원 변동 내역을 모두 조회한다.
- two pointer 알고리즘을 통해 지출 내역과 인원 변동 내역의 순서를 정렬하여 반환한다.

## 중점적으로 리뷰받고 싶은 부분(선택)

## 논의하고 싶은 부분(선택)

## 🫡 참고사항

2024-07-23 04:58 UTC, Todari commented
PR 이름 이슈 이름이랑 똑같이 해주세용~!~!

2024-07-23 06:42 UTC, Arachneee requested changes
BillActions 랑 MemberActions를 정렬하는 로직이 많이 복잡하네요.
해결할 수 있는 방법을 같이 고민해보죠

2024-07-23 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/presentation/response/ActionResponse.java
> +        return new ActionResponse(actionAppResponse.actionId(),
```suggestion
        return new ActionResponse(
                actionAppResponse.actionId(),
```

2024-07-23 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
> +        return new ActionAppResponse(memberAction.getAction().getId(),
```suggestion
        return new ActionAppResponse(
                memberAction.getAction().getId(),
```

2024-07-23 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/EventService.java
> +                                                                 List<MemberAction> memberActions) {
```suggestion
    private static List<ActionAppResponse> getActionAppResponses(
            List<BillAction> billActions,
            List<MemberAction> memberActions
    ) {
```

2024-07-23 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/EventService.java
> +        }
r: 해당 로직이 정렬을 하고 있다는 것이 표현되었으면 좋겠어요.

2024-07-23 06:42 UTC, Arachneee commented on server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
> +        return new ActionAppResponse(billAction.getAction().getId(),
DITTO

2024-07-24 00:54 UTC, khabh requested changes
멋져요

2024-07-24 00:54 UTC, khabh commented on server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
> +            if (memberActionStatus.name().equals("IN")) {
```suggestion
            if (memberActionStatus == MemberActionStatus.IN) {
```
r: 그럴 가능성이 낮긴 하지만 MemberActionStatus.IN의 이름이 변경될 경우에 단축키로 한 번에 변경할 수 있으니 문자열보다는 enum으로 직접 비교하는 것이 더 좋을 것 같아요~

2024-07-24 00:54 UTC, khabh commented on server/src/main/java/server/haengdong/application/EventService.java
> +        List<ActionAppResponse> result = new ArrayList<>();
r: result 대신 actionsResponse나 actions 같이 조금 더 구체적인 변수명을 지어 주세요 :)

2024-07-24 00:54 UTC, khabh commented on server/src/test/java/server/haengdong/presentation/EventControllerTest.java
> +                .andExpect(jsonPath("$.actions[1].type").value("BILL"));
```suggestion
        List<ActionAppResponse> actionAppResponses = List.of(ActionAppResponse.of(memberAction),
                ActionAppResponse.of(billAction));
        given(eventService.findActions(token)).willReturn(actionAppResponses);

        ActionsResponse expectedActions = ActionsResponse.of(actionAppResponses);
        String expectedJson = objectMapper.writeValueAsString(expectedActions);

        mockMvc.perform(get("/api/events/" + token + "/actions"))
                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(content().json(expectedJson));
```
c: 이렇게 수정하면 다른 테스트랑 컨벤션이 다르긴 한데 ㅎㅎ... 여기 andExpect가 너무 많아요 알잘딱깔쎈 해 주세요

2024-07-24 00:54 UTC, khabh commented on server/src/main/java/server/haengdong/application/EventService.java
> +    private static List<ActionAppResponse> getActionAppResponses(List<BillAction> billActions,
c: 큐 사용하면 index 연산 안 해도 돼서 코드 좀 더 깔끔해질 것 같습니당

2024-07-25 07:05 UTC, kunsanglee commented on server/src/test/java/server/haengdong/presentation/EventControllerTest.java
> +                .andExpect(jsonPath("$.actions[1].type").value("BILL"));
감자가 어떤 의미로 코멘트 달았는지 이해하지만, 테스트 검증부를 개발자가 못보는 것이 어색해서 현재 코드 유지하려고 합니다. 👍

2024-07-25 09:04 UTC, Arachneee approved these changes

2024-07-25 09:04 UTC, khabh approved these changes

2024-07-25 09:05 UTC, merged