[FE] 성능 개선 : Preconnect to requered origins
woowacourse-teams/2024-haeng-dong pull request #771
Opened 2024-10-18 08:19 UTC by soi-ha

## issue
- close #768 

## 구현 목적

lighthouse를 실행한 결과 다음과 같은 진단이 나왔습니다.

<img width="633" alt="행동대장_폰트_개선전_lighthouse진단" src="https://github.com/user-attachments/assets/e48c47c4-458e-4a18-9a9c-3fde24e8fd67">

이런 진단의 이유는 우리 서비스에서 사용하는 Pretendard 폰트가 preconnect 되지 않아서 발생한 것이었습니다. 따라서 Pretendard 폰트를 preconnect하여 320ms를 절감합니다.

## 개선 전/후

### 개선 전

개선 전의 네트워크 요청을 확인해보면 Pretendard.css는 뒤늦게 다운로드 되는 것을 확인할 수 있습니다.

<img width="768" alt="행동대장_폰트_개선전_네트워크요청" src="https://github.com/user-attachments/assets/e3c00aff-79e9-401c-b802-133735ffcf14">
<img width="692" alt="행동대장_폰트_개선전_lighthouse" src="https://github.com/user-attachments/assets/86227585-4db2-41b2-bdf0-f1c5cddd1bf4">

### 개선 후

개선 후의 네트워크 요청을 확인해보면 Pretendard.css는 조기에 다운로드되는 것을 확인할 수 있습니다. 추가로 lighthouse 진단에서 발생하던 `필수 원본 미리 연결하기`가 사라진 것을 확인할 수 있습니다.

<img width="761" alt="행동대장_폰트_개선후_네트워크요청" src="https://github.com/user-attachments/assets/814fa2bf-e29b-41de-a81b-4abe960a9cd0">
<img width="698" alt="행동대장_폰트_개선후_lighthouse" src="https://github.com/user-attachments/assets/182e2a99-fce8-43d5-9516-717179b325e7">

## 개선 방법

이전에는 GlobalStyle.ts에서 import를 통해 font link를 불러오고 있었습니다. 또한, font import는 예전 디자인 시스템 GlobalStyle.ts과 src 하위 GlobalStyle.ts, 총 2번 호출하고 있었습니다. 현재는 디자인시스템을 따로 배포하여 사용하지 않기 때문에 두 GlobalStyle.ts에서 font import를 제거했습니다.

font를 preconnect와 dns-prefetch를 하기 위해 index.html에서 직접 font link를 import 했습니다. 기존 코드들과의 통일서을 위해서 React 컴포넌트 단에서 useEffect를 활용하여 font를 import하는 방법도 존재했습니다. 아니면 React 컴포넌트에서 head 태그에 접근하기 위해서 라이브러리를 활용하는 방법도 있었습니다. 다만 font를 preconnect 하기 위해 Helmet 라이브러리와 useEffect를 사용하는 것은 효율성이 좋지 않다고 판단했습니다.

따라서 index.html에 직접 font link를 import하게 되었습니다.

```html
<link rel="preconnect" href="https://cdn.jsdelivr.net" />
<link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" rel="stylesheet" />
```

## 논의하고 싶은 사항
사실 index.html에 직접 link 태그를 넣어서 개선해도 괜찮나.. 고민이 됐습니다. React에서 할 수 있는 방법을 하고 싶었으나.. 찾은 내용들이 너무 비효율적이라고 판단해서 결국에는 index.html에 넣었습니다.. 이 방법이 괜찮으신지.. 여러분의 의견이 궁금합니다!

2024-10-22 11:23 UTC, jinhokim98 approved these changes
어떻게 보면 간단한 방식이지만 의미있는 개선이 된 것 같아 저는 좋은 개선 방식이라 생각합니다.
고생했어요!

2024-10-22 11:23 UTC, jinhokim98 commented on client/src/components/Design/theme/GlobalStyle.ts
> -  @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
폰트 요청 두 번 보내는 것 이상하다고 여겼는데 행디에서 문제가 있었네요. 발견 감사합니다~

2024-10-22 11:23 UTC, jinhokim98 commented on client/index.html
> +    <link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" rel="stylesheet" />
저는 index.html에 넣어서 개선하는 방식 좋은 것 같아요. 어느 페이지든 폰트는 필요하니깐요!

2024-10-22 18:51 UTC, pakxe approved these changes
성능 최적화라는 테스크를 포비의 조언대로 팀단위로 올려서 해보게 되었는데 결과가 너무 좋네요! 덕분에 MainPage 성능이 굉장히 좋아졌습니다. ㅎㅎㅎㅎ 최적화 방법과 그 방법을 실제로 적용하느라 고생많았어요~!

2024-10-22 18:51 UTC, pakxe commented on client/index.html
> +    <link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" rel="stylesheet" />
혹시 인덱스에 link태그를 넣는게 문제가 될게 어떤 것들이 있나요?

2024-10-22 18:51 UTC, pakxe commented on client/src/GlobalStyle.ts
> -  @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
wow.. 👍👍👍

2024-10-23 04:03 UTC, soi-ha commented on client/index.html
> +    <link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" rel="stylesheet" />
link 태그를 넣는게 문제여서 고민되었다기 보다는 대부분의 코드가 react로 작성되었기 때문에 코드 통일성을 해칠까봐 고민되었어요! 문제될만한 것들은 없습니다!

2024-10-23 05:13 UTC, Todari requested changes
꼼꼼하게 체크하고 성능 개선을 진행해 줘서 정말 감사해요~!
달았던 comment 중에, storybook 관련 내용이 있었는데,
아마 지난번처럼 local 폰트 중 pretendard가 없는 모바일 환경 등에선 제대로 적용되지 않을거에요.
일단, 모바일로 확인해 보지 못해서 사파리로 확인해 봤을 땐, 아래처럼 폰트가 깨지는 걸 확인할 수 있었네요.
배포 전까지 해결이 가능하다면, 부탁드려요!

![image](https://github.com/user-attachments/assets/52e8ede8-69ac-4823-b8ea-c245c50cf8d9)

2024-10-23 07:22 UTC, Todari commented
변경사항 확인했습니다~! approve 🚀🚀🚀🚀

2024-10-23 07:22 UTC, soi-ha commented on client/src/components/Design/theme/GlobalStyle.ts
>      display: revert;
스토리북에서 폰트가 적용되지 않는 것을 확인했습니다! 
수정해서 올렸어용!

2024-10-23 07:22 UTC, Todari approved these changes

2024-10-23 07:26 UTC, merged