[FE] v2.1.1에서 구현한 랜딩페이지 개선
woowacourse-teams/2024-haeng-dong pull request #777
Opened 2024-10-21 13:18 UTC by Todari

## issue
- close #764 

## 구현 목적
- 기존 랜딩페이지에서 누락된 부분(만든사람들 section)이 존재합니다. 
- 화면의 최하단 스크롤 시 배경 이미지가 보여 어색한 부분이 있습니다.
- ios에서 svg의 이미지들이 깨져서 보이는 문제가 있습니다.
- feature들의 섹션이 세로로 너무 길다고 판단하여, 가로로 스크롤 되는 feature container section을 별도로 생성하고자 합니다.
- 기존 svg image들 중에, 비트맵 파일을 포함하고 있는 svg가 있었고, 이 용량이 너무 커서 파일을 다시 제작하였습니다.

## 구현 사항
### 1. 만든사람들 section 제작
- 디바이스 해상도에 따라 변경되는 반응형 레이아웃을 구현하였습니다.

https://github.com/user-attachments/assets/5c1b480e-48a5-4f5a-a7a4-f84a6a215f11

### 2. 최하단 스크롤 시 배경이미지 보이지 않도록 변경
```tsx
// 13:22:src/hooks/useMainSectionBackgroundScroll.ts
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      setIsVisible(window.scrollY <= window.innerHeight);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);
```

```tsx
// 53:59:src/pages/MainPage/Section/MainSection/MainSection.style.ts
export const backgroundImageStyle = (isVisible: boolean) =>
  css({
    objectFit: 'cover',
    height: '100vh',
    width: '100vw',
    opacity: isVisible ? 1 : 0,
  });
```

- `mainSection`에서 scroll이 100vh 보다 더 많이 될 경우, backgroundImage의 opacity를 0으로 조절하여 첫 화면을 벗어난 뒤에는 배경 이미지가 보이지 않도록 변경하였습니다.

### 3. ios svg가 깨지는 문제
- img 태그 내부에 svg 소스를 넣어주게 되면, ios에서 이를 비트맵 방식으로 렌더하는 경우가 있습니다.
- 애플 디스플레이의 경우 3~4배수의 DPI를 사용하므로 이 과정에서 3~4배의 픽셀 저하 현상이 발생할 수 있습니다.
- 렌더링 과정에서 이를 비트맵으로 처리하지 않게 하기 위해서 `<img>` 태그가 아닌, `<object>`태그를 이용하여 svg 파일을 넘겨주였습니다.

**개선 전**
```tsx
<img src={`${process.env.IMAGE_URL}/feature1.svg`} css={imageStyle} />
```

**개선 후**
```tsx
<object type="image/svg+xml" data={`${process.env.IMAGE_URL}/feature1.svg`} css={imageStyle} />
```

### 4. 좌로 스크롤되는 featureSection 구현
```tsx
// 3:33:src/hooks/useMainPageYScroll.ts
const useMainPageYScroll = () => {
  const featureSectionRef = useRef<HTMLDivElement>(null);
  const translateX = useRef(0);

  useEffect(() => {
    const handleScroll = () => {
      if (featureSectionRef.current) {
        const featureSectionTop = featureSectionRef.current.offsetTop;
        const scrollY = window.scrollY;

        if (scrollY >= featureSectionTop && translateX.current < window.innerWidth * 4) {
          window.scrollTo(0, featureSectionTop);
          translateX.current += scrollY - featureSectionTop;
          const newTransform = `translateX(calc(200vw - ${translateX.current > 0 ? translateX.current : 0}px))`;
          featureSectionRef.current.style.transform = newTransform;
        }
        if (scrollY <= featureSectionTop && translateX.current > 0) {
          window.scrollTo(0, featureSectionTop);
          translateX.current += scrollY - featureSectionTop;
          const newTransform = `translateX(calc(200vw - ${translateX.current < window.innerWidth * 4 ? translateX.current : window.innerWidth * 4}px))`;
          featureSectionRef.current.style.transform = newTransform;
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return {featureSectionRef};
};
```

- `featureSection`의 상단에 스크롤이 도달하면, `window.scrollTo(0, featureSectionTop)`을 통해 스크롤y 위치를 `featureSection` 상단에 고정합니다.
- `scrollY`가 증가한 만큼 `translateX`에 더해줍니다.
- 증가한 `translateX` 만큼 `featureSectionRef`를 transfomX 시킵니다.

2024-10-22 11:43 UTC, jinhokim98 approved these changes
덕분에 메인페이지를 유려한 애니메이션과 함께 보여줄 수 있을 것 같아요! 고생했습니다~~

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/hooks/useMainPageYScroll.ts
> +          const newTransform = `translateX(calc(200vw - ${translateX.current > 0 ? translateX.current : 0}px))`;
top속성 대신에 translateX를 사용해서 reflow가 일어나지 않게 신경써주신 점 너무 좋아요!

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/hooks/useMainPageYScroll.ts
> +    return () => window.removeEventListener('scroll', handleScroll);
개인적인 의견이지만 scroll이벤트도 좋지만 IntersectionObserver를 이용해보는 것도 좋지 않을까 싶어요!

https://developer.mozilla.org/ko/docs/Web/API/Intersection_Observer_API

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/hooks/useMainSectionBackgroundScroll.ts
> +    return () => window.removeEventListener('scroll', handleScroll);
이 부분도 IntersetionObserver를 이용해서 마지막 section이 viewport에 관측되면 visible을 false로 줘도 좋을 것 같아요!

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/pages/MainPage/MainPage.tsx
> +  const {featureSectionRef} = useMainPageYScroll();
useMainPageYScroll을 MainPage가 아니라 FeatureSection에서 호출해도 되지 않을까 생각합니다!!

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/pages/MainPage/Section/CreatorSection/CreatorSection.style.ts
> +  },
640px부터는 flex로 한 줄로 보여지는 건가요?

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
> +    <button
이것도 개인적인 의견이지만 버튼을 눌렀을 때 링크로 이동하는 기능이라면 a태그도 괜찮아보입니다!

2024-10-22 11:43 UTC, jinhokim98 commented on client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
> +        <object type="image/svg+xml" data={`${process.env.IMAGE_URL}/feature2.svg`} css={imageStyle} />
이런 태그가 있다는 것 처음 알았어요.. 덕분에 배워갑니다🙇‍♂️

2024-10-22 18:36 UTC, pakxe requested changes
이런 기상천외한 방법을 생각하시다니 역시 멋진 토다리...!!! 다양한 디바이스에서 보여질 것도 상정하고 개발하느라 고생많았습니다. 그리고 색다른 사용 경험을 위해 수평방향의 스크롤이 생겼네요! 사용자 입장에선 재밌는 요소라고 생각합니다 ㅎ,ㅎ 수고했어요 😆

그런데 모바일과 데스크탑(+마우스휠)에서 옆으로 이동되는 Feature부분이 부자연스러운 것 같아요. 

https://github.com/user-attachments/assets/fdfc92c7-4402-4f83-9e9a-6bf61dc65f85

모바일에서는 속도가 굉장히 빠르고, 화면이 여기저기로 이동됩니다. 그리고 밑에 프로젝트 참여자부분으로 스크롤이 옮겨졌다가 재정립되는 그 시간 차가 꽤나 커서 사용자들에게 의아함을 줄 것 같아요.

그리고 데스크탑(+마우스휠)환경에서도 비슷하게 프로젝트 참여자부분이 계속 보였다 안보였다 하는 문제가 있습니다. 반대로 스크롤할 때도 마찬가지로 위 영역이 보였다안보였다 하는 문제가 있어요.

2024-10-22 18:36 UTC, pakxe commented on client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
> +    <button
접근성에 더 좋을 것 같네요..!

2024-10-22 18:36 UTC, pakxe commented on client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
> +        },
css를 분리하는건 어떨까유..?!
개인적으로는 분리하는게 더 컴포넌트 구조를 파악하기 수월하다고 생각해요

2024-10-22 18:36 UTC, pakxe commented on client/src/pages/MainPage/Section/CreatorSection/CreatorSection.tsx
> +        행동대장을 만든 행동대장들
꺄올

2024-10-22 18:36 UTC, pakxe commented on client/src/pages/MainPage/Section/CreatorSection/CreatorSection.tsx
> +          <Avatar imagePath="soha" name="소하" onClick={() => window.open('https://github.com/soi-ha', '_blank')} />
링크를 다 넣어주셨군요..! 감덩.....🥹

2024-10-22 18:36 UTC, pakxe commented on client/src/pages/MainPage/Section/CreatorSection/CreatorSection.tsx
> +          <Avatar imagePath="todari" name="토다리" onClick={() => window.open('https://github.com/Todari', '_blank')} />
객체 배열로 만들고 `arr.map(info => <Avatar {...info}/>` 처럼 바꿔보는건 어떨까요?

2024-10-23 02:05 UTC, soi-ha requested changes
토다리가 만들어준 랜딩페이지 덕분에 랜딩 페이지만 봐도 진짜 개 짱 멋있는 서비스 같아 보이네요!

다만, 웨디와 동일한 이유로 RC를 드렸어요~ 아무래도 모바일 웹이 퍼스트다보니.. 꼭 수정된 후에 배포가 되어야 할 것 같아요!

2024-10-23 02:05 UTC, soi-ha commented on client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
> +        <object type="image/svg+xml" data={`${process.env.IMAGE_URL}/feature2.svg`} css={imageStyle} />
갤릭시와 데스크탑에서는 svg 이미지가 안 깨졌는데 ios에서만 깨지는 이유를 파악하여 해결해주셨다니.. 징초ㅑ 최고에요!

그렇다면 행댕이 svg 이미지에서도 위와 같은 방식으로 적용하면 모두 해결될까요?!

2024-10-23 02:05 UTC, soi-ha commented on client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.style.ts
> +  // backgroundColor: '#DFC1FF',
👀

2024-10-23 02:05 UTC, soi-ha commented on client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
> +  aspectRatio: '1/1',
Flutter만을 위한 코드인건가요?!

만약 Flutter만을 위한 코드라면 모바일 웹 코드와 같이 작성해두어도 괜찮을지 고민이네용

2024-10-23 06:11 UTC, Todari commented on client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
> +  aspectRatio: '1/1',
아니용~ flutter를 위한 코드는 아니었고, img 태그를 object 로 바꾸면서, image의 사이즈가 적용되는 방식이 변경되어서 추가된 코드입니다!

2024-10-23 07:40 UTC, pakxe approved these changes

2024-10-23 07:41 UTC, soi-ha approved these changes
반영해주신 부분 확인했습니다!
빠르게 반영해줘서 고마워용!

2024-10-23 07:41 UTC, soi-ha commented on client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
> +    <a href={navigateUrl} target="_blank" css={avatarStyle}>
크하 ~ 편안합니댜

2024-10-23 07:41 UTC, soi-ha commented on client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
> +        <object type="image/svg+xml" data={`${process.env.IMAGE_URL}/feature2.svg`} css={imageStyle} />
저런... 행댕이 ios에서 깨지는 부분은 더 찾아봐야겠네욯

2024-10-23 07:49 UTC, merged