[FE] 로그인 상태라면 행사 생성시 로그인 페이지를 띄우지 않음
woowacourse-teams/2024-haeng-dong pull request #857
Opened 2024-12-16 13:10 UTC by pakxe

## issue
- close #855 

## 구현 목적
최근에 로그인 했다면 다시 로그인 페이지를 띄우지 않고 바로 행사 생성을 할 수 있도록 합니다. 

## 구현 사항
로그인 여부는 쿠키에 저장됩니다. 
다만 쿠키를 클라이언트가 확인할 수 없기 때문에, 로그인 여부가 포함된 `회원 정보 확인 api`를 호출해 로그인 여부를 확인합니다.

`회원 정보 확인 api`를 호출하는 시점은 "정산 시작하기"버튼을 눌렀을때로 하려다가,  api 호출이 오래걸리면 MainPage에 계속 머물러있는게 이상할 것 같아서 MainPage 진입 시 호출하도록 했습니다. 

이를 위해 현재 MainPage에서 tanstackquery호출이 안되도록 분리해놓았던 것을 예전대로 롤백시켜놓았습니다.

그리고 현재 회원 정보 확인 api가 나와있지 않은 상황이므로 msw를 사용하여 테스트했습니다.

2024-12-16 15:03 UTC, jinhokim98 approved these changes
웨디 고생했습니다~~~ 저는 /api/users/mine 정상적으로 호출했는데 이상하네요;;; 나중에 이야기해봐요! 코멘트 조금 달았습니다! 별건 없긴한데;; Approve할게요

2024-12-16 15:03 UTC, jinhokim98 commented on client/src/types/serviceType.ts
> +};
이것도 저랑 겹칠 것 같아요ㅋㅋ

2024-12-17 05:17 UTC, pakxe commented on client/src/apis/request/auth.ts
> +// 아직 안나온 api라 임의로 두었음
지금 dev 서버가 없어졌죠..? 그래서 그런 것 같네용. prod로 하니까 잘 됩니다..ㅋㅎㅎ

2024-12-17 05:17 UTC, pakxe commented on client/src/mocks/handlers/authHandlers.ts
> +        nickname: '크리스마스',
All I Want For Christmas Is You~~~

2024-12-17 05:18 UTC, pakxe commented on client/src/types/serviceType.ts
> +};
아이고야

2024-12-17 07:16 UTC, Todari requested changes
웨디~!~! 바쁠텐데 고생 많았어요.
코드를 확인해 봤는데, 구현이 잘못되어 있는 것 같아요!
메인페이지에서 user/mine api의 `isGuest` 요청 결과를 사용해서 login 화면 및 생성 화면으로 이동하는 로직이 있는데,
이 `isGuest` 는 카카오로그인이면 false, 비회원로그인이면 true로 반환되어요.

그래서 현재 웨디가 구현한 부분을 실행해보면 아래와 같아요.
1. 카카오 로그인
2. 행사생성
3. 홈으로 이동 (/api/user/mine API 호출 -> isGuest : false)
4. 정산 시작하기 버튼 클릭
5. 로그인 페이지로 이동

반면, 카카오 로그인이 아니라 비회원 생성을 한다면,
1. 비회원 로그인
2. 행사생성
3. 홈으로 이동 (/api/user/mine API 호출 -> isGuest : true)
4. 정산 시작하기 버튼 클릭
5. 행사 생성 페이지로 이동

처럼 작동해요!

혹시 제가 애초에 처음 구현 의도를 제대로 파악하지 못한거였다면 미안해요...
제가 느끼기에는 카카오로그인, 비회원로그인 모두 로그인 되어 있는 정보가 있다면 로그인 창을 건너뛰는게 맞다고 생각했어요!

2024-12-17 12:51 UTC, soi-ha approved these changes
구현해주신 부분 잘 확인했어요! 웨디~!
저번에 소셜 로그인 기능이 추가되면서 웨디가 구현해준 부분은 꼭 필요했는데.. 잘 반영해줘서 고마워요!

2024-12-17 12:51 UTC, soi-ha commented on client/src/apis/endpointPrefix.ts
> +export const MEMBER_API_PREFIX = '/api/users';
순간 제가 추가해둔 코드가 반영된 줄 알고 확인하고 와써욪.. 동일한 생각을 하셨군여

2024-12-17 12:51 UTC, soi-ha commented on client/src/apis/request/auth.ts
> +export const requestGetUserInfo = async () => {
저는 user와 관련된 부분은 user.ts 파일을 생성하여 작성해줬는데요! 이 코드 또한 user.ts 파일로 가도 좋을 것 같네용!
merge할 때 같이 논의해봐요~!

2024-12-17 12:51 UTC, soi-ha commented on client/src/apis/request/event.ts
>  export const requestPatchUser = async (args: RequestPatchUser) => {
이 부분 또한 저도 웨디와 동일하게 변경해줬어요!
다만 해당 코드도 event.ts 파일보다 user.ts 파일에 이동되는건 어떨지 논의해봐요!

2024-12-17 13:08 UTC, pakxe commented on client/src/apis/endpointPrefix.ts
> +export const MEMBER_API_PREFIX = '/api/users';
ㅋㅋㅋㅋㅋㅋㅋㅋ역시 다 똑같은 생각을 하고있었습니다

2024-12-17 13:09 UTC, pakxe commented on client/src/apis/request/auth.ts
> +export const requestGetUserInfo = async () => {
오 좋네요 API PREFIX도 나눠두었으니까 파일을 나눠도 괜찮겠습니다

2024-12-17 13:11 UTC, pakxe commented
@Todari 

토다리 코멘트 남겨준 부분을 반영완료했습니다! 
그리고 로그인 페이지가 보여지는 플로우에 관해서는 다이어그램을 참고해주세요!!~

비회원으로 계속하기는 사실 비회원 로그인이 아니라 행사를 위한 일회용 회원이기 떄문에 로그인 페이지가 떠야 된다고 생각했어요. 그래서 isGuest가 false인 경우만 로그인 페이지가 안뜨도록 하였고, 그 외 경우에는 전부 로그인 페이지가 뜨도록 했습니다!

2024-12-18 05:29 UTC, Todari approved these changes
https://github.com/woowacourse-teams/2024-haeng-dong/commit/711e33a8fa6ab18e343997a088b0b7c9dd6dcfa5

확인 완료햇서요~! 추가적인 업무까지 고생 많았습니다~!
**대 황 빡 쎄 웨 디**

2024-12-18 07:36 UTC, merged