[FE] 앱 설치 되어있음에도 deep link 대체 링크가 실행되는 버그 해결
woowacourse-teams/2024-haeng-dong pull request #886
Opened 2024-12-30 06:28 UTC by jinhokim98

## issue
- close #885 

### 버그 상황
이전에는 사용자가 버튼을 클릭한 뒤 1.5초 뒤에 대체 링크를 띄우는 것으로 작성했었습니다.
앱이 설치되었다면 1.5초 안에 실행될 것이라 생각하여 기능을 작성했는데 문제가 발생했습니다.

- 앱이 설치되었음에도 1.5초 이상이 걸리는 순간이 존재
- 앱을 다녀온 뒤에 다시 접속 시 대체 링크 실행

### 해결책 1 : 설치됨을 확인하는 시간 늘리기
기존 1500ms에서 여유를 두어 2500ms로 시간을 늘렸습니다. 1초 정도 시간의 여유를 두어 늦게 실행되는 환경에도 대처하게 했습니다.

### 해결책 2 : document visibility state를 사용해서 화면이 보여지고 있는지 조건 추가

[document visibilityState api](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState)를 사용하면 사용자가 현재 화면을 보고 있는 지를 검사할 수 있습니다. 값은 visible, hidden이 있으며 hidden이 되면 사용자가 화면을 보고 있지 않다는 것입니다.

이를 사용하여 앱이 설치되지 않은 조건을 강화했습니다. 단순히 "2.5초가 지났음"에 더해 "2.5초가 지났음에도 현재 화면을 보고 있음"을 검증하도록 했습니다.

사용자가 버튼을 클릭하면 현재 시간을 초기화하고 setTimeout을 실행하여 2.5초가 지났을 때 콜백을 실행하는데 위 조건에 만족하면 앱이 설치되지 않았을 때 대처가 가능하도록 기능을 작성했습니다.

### 대체 링크 대신 토스트만 띄우도록 변경
대체 링크(앱 스토어)에 들어가 앱을 설치하고 송금 준비를 한 뒤 기능을 이용하는 것과 다른 앱을 사용하는 것을 비교했을 때 후자의 의견이 더 많았습니다. 굳이 이 기능을 이용하기 위해 사용하지 않았던 앱의 초기 설정을 하지 않는다는 이유였습니다. 그래서 앱 스토어로 이동하지 않고 단순히 `앱이 설치되지 않았어요. 다른 앱을 사용해주세요.` 라는 토스트를 띄우는 것으로 변경했습니다.

## 🫡 참고사항

2025-01-02 04:22 UTC, pakxe approved these changes
`2.5초뒤 && 화면 보고있음` 조건이면 토스트를 띄우는 것이군요. 좋은 것 같습니다! 👍 👍 
화면 보고있는지 여부를 훅으로 분리해도 깔끔하고 좋을 것 같다는 생각이 들어요

2025-01-03 02:27 UTC, soi-ha requested changes
쿠키! 개선해주신 방향의 코드 너무 잘 봤습니다! 다만, 제가 이해되지 않는 부분이 있어서 그 부분에 대해 답변을 받고 싶어 RC 드렸어요! 확인 부탁드려용~ 😊

2025-01-03 02:27 UTC, soi-ha commented on client/src/hooks/useNavigateApp.ts
> +        Date.now() - time >= (installThresholdTime ?? DEFAULT_INSTALL_THRESHOLD_TIME) &&
설치되었는지 확인하는 시간과 현재 화면을 보고 있는지. 두가지로 확인하고 toast를 띄우는 방식은 좋은 것 같아요! 그리고 설치됐는지 확인하는 시간이 바뀔 수도 있음을 고려하여 개발한 부분은 정말 센스 👍 멋집니댱!

2025-01-03 02:27 UTC, soi-ha commented on client/src/hooks/useNavigateApp.ts
> +    return () => document.addEventListener('visibilitychange', clearTime);
document.addEventListener('visibilitychange', clearTime) 코드문이 두번 실행되는 이유가 무엇때문인가용??

2025-01-03 04:07 UTC, Todari commented on client/src/hooks/useNavigateApp.ts
> +        Date.now() - time >= (installThresholdTime ?? DEFAULT_INSTALL_THRESHOLD_TIME) &&
소하 말대로, 클린업 함수에서는 removeEventListener이 되어야 맞는 것 같아요!

2025-01-03 04:08 UTC, Todari approved these changes
cleanup 함수 부분만 수정되면 될 것 같네요!!!
고마워용 쿠키 approve 할게욘~!

2025-01-03 06:08 UTC, jinhokim98 commented on client/src/hooks/useNavigateApp.ts
> +        Date.now() - time >= (installThresholdTime ?? DEFAULT_INSTALL_THRESHOLD_TIME) &&
발견 감사합니다~~ 놓쳤어요;;;

2025-01-03 06:10 UTC, soi-ha approved these changes
👍

2025-01-03 06:52 UTC, merged